Repository apache/skywalking-banyandb, pull requests merged in 2022-03, with the labels that each got.

#88 Add the location to the start time parser
  banyand/tsdb/segment.go
Labels: bug

#89 Add measure query
  api/proto/banyandb/database/v1/rpc_grpc.pb.go
  api/proto/banyandb/measure/v1/query.pb.go
  api/proto/banyandb/measure/v1/query.proto
  api/proto/banyandb/measure/v1/rpc_grpc.pb.go
  api/proto/banyandb/stream/v1/rpc_grpc.pb.go
  banyand/liaison/grpc/stream_test.go
  banyand/measure/measure_write_test.go
  banyand/query/processor.go
  banyand/query/processor_test.go
  banyand/stream/metadata.go
  banyand/tsdb/bucket/bucket.go
  banyand/tsdb/shard_test.go
  pkg/pb/v1/query.go
  pkg/query/executor/interface.go
  pkg/query/logical/common.go
  pkg/query/logical/common_test.go
  pkg/query/logical/expr.go
  pkg/query/logical/format.go
  pkg/query/logical/interface.go
  pkg/query/logical/measure_analyzer.go
  pkg/query/logical/measure_analyzer_test.go
  pkg/query/logical/measure_plan_execution_test.go
  pkg/query/logical/measure_plan_indexscan_local.go
  pkg/query/logical/plan_orderby.go
  pkg/query/logical/schema.go
  pkg/query/logical/stream_analyzer.go
  pkg/query/logical/stream_analyzer_test.go
  pkg/query/logical/stream_plan.go
  pkg/query/logical/stream_plan_execution_test.go
  pkg/query/logical/stream_plan_indexscan_global.go
  pkg/query/logical/stream_plan_indexscan_local.go
  pkg/query/logical/testdata/measure_query_data.json
  pkg/test/measure/testdata/index_rule_binding.json
  pkg/test/measure/testdata/index_rules/scope.json
  pkg/test/measure/testdata/measure.json
  scripts/build/base.mk
Labels: enhancement

#90 Add a prefix to the root path
  banyand/liaison/grpc/stream_test.go
  banyand/measure/measure_suite_test.go
  banyand/measure/service.go
  banyand/query/processor_test.go
  banyand/stream/service.go
  banyand/stream/stream_suite_test.go
  pkg/query/logical/common_test.go
Labels: bug

#91 Add the TopNAggregation schema registration
  api/proto/banyandb/database/v1/rpc.pb.go
  api/proto/banyandb/database/v1/rpc.proto
  api/proto/banyandb/database/v1/rpc_grpc.pb.go
  banyand/liaison/grpc/registry.go
  banyand/liaison/grpc/server.go
  banyand/metadata/metadata.go
  banyand/metadata/metadata_test.go
  banyand/metadata/schema/etcd.go
  banyand/metadata/schema/group.go
  banyand/metadata/schema/index.go
  banyand/metadata/schema/measure.go
  banyand/metadata/schema/schema.go
  banyand/metadata/schema/stream.go
  banyand/metadata/schema/topn.go
Labels: enhancement, api

#94 Support top function on measure querying
  api/proto/banyandb/measure/v1/query.pb.go
  api/proto/banyandb/measure/v1/query.proto
  pkg/pb/v1/query.go
  pkg/query/aggregation/function.go
  pkg/query/logical/interface.go
  pkg/query/logical/measure_analyzer.go
  pkg/query/logical/measure_analyzer_test.go
  pkg/query/logical/measure_plan_aggregation.go
  pkg/query/logical/measure_plan_execution_test.go
  pkg/query/logical/measure_plan_groupby.go
  pkg/query/logical/measure_plan_indexscan_local.go
  pkg/query/logical/measure_plan_top.go
  pkg/query/logical/measure_top.go
  pkg/query/logical/measure_top_test.go
  pkg/query/logical/testdata/measure_top_data.json
Labels: enhancement, api
