Repository apache/skywalking-banyandb, pull requests merged in 2022-11, with the labels that each got.

#202 Fix bugs of tsdb
  Makefile
  banyand/tsdb/block.go
  banyand/tsdb/bucket/bucket.go
  banyand/tsdb/bucket/strategy.go
  banyand/tsdb/bucket/strategy_test.go
  banyand/tsdb/segment.go
  banyand/tsdb/series.go
  banyand/tsdb/seriesdb.go
  banyand/tsdb/shard.go
  banyand/tsdb/shard_test.go
  banyand/tsdb/tsdb.go
  banyand/tsdb/tsdb_test.go
  pkg/timestamp/range.go
  test/cases/stream/data/testdata/service_cpm_minute_data.json
Labels: bug

#205 Changes for releasing v0.2.0
  CHANGES.md
  README.md
  scripts/release.sh
Labels: documentation

#198 Add data-model.md to explian objectes in API
  docs/concept/data-model.md
  docs/crud/property.md
  docs/menu.yml
  docs/schema.md
Labels: documentation

#206 Fix build guidance for 0.2
  CONTRIBUTING.md
  docs/installation.md
Labels: bug, documentation

#207 Clean up invalid todos
  banyand/metadata/schema/etcd.go
  banyand/tsdb/seriesdb.go
  pkg/query/logical/measure/schema.go
  pkg/query/logical/schema.go
  pkg/query/logical/stream/schema.go
Labels: chore

#209 Fix CVE-2022-32149
  dist/LICENSE
  dist/licenses/license-golang.org-x-xerrors.txt
  go.mod
  go.sum
Labels: dependencies, vulnerability

#212 Sync the block opening
  .github/workflows/ci.yml
  .github/workflows/flaky-test.yml
  .github/workflows/slow-test.yml
  .github/workflows/test.yml
  Makefile
  banyand/tsdb/block.go
  banyand/tsdb/block_ctrl.go
  banyand/tsdb/bucket/bucket.go
  banyand/tsdb/bucket/queue.go
  banyand/tsdb/bucket/queue_test.go
  banyand/tsdb/bucket/strategy.go
  banyand/tsdb/bucket/strategy_test.go
  banyand/tsdb/metric.go
  banyand/tsdb/retention.go
  banyand/tsdb/scope.go
  banyand/tsdb/segment.go
  banyand/tsdb/segment_ctrl.go
  banyand/tsdb/shard.go
  banyand/tsdb/shard_test.go
  banyand/tsdb/tsdb.go
  banyand/tsdb/tsdb_suite_test.go
  banyand/tsdb/tsdb_test.go
  pkg/run/closer.go
  pkg/timestamp/scheduler.go
  test/integration/cold_query/query_suite_test.go
  test/integration/other/other_suite_test.go
  test/integration/query/query_suite_test.go
Labels: bug, testing

#213 Add health checker to test cases
  .licenserc.yaml
  banyand/liaison/grpc/registry_test.go
  banyand/tsdb/shard_test.go
  pkg/grpchelper/client.go
  pkg/test/helpers/grpc_health.go
  pkg/test/measure/etcd.go
  pkg/test/measure/traffic/traffic.go
  pkg/test/stream/etcd.go
  pkg/test/stream/traffic/traffic.go
  test/integration/cold_query/query_suite_test.go
  test/integration/load/load_suite_test.go
  test/integration/other/measure_test.go
  test/integration/other/property_test.go
  test/integration/other/tls_test.go
  test/integration/query/query_suite_test.go
Labels: testing

#215 Correct time line of arbitrary block testing
  banyand/liaison/grpc/registry_test.go
  banyand/measure/metadata_test.go
  banyand/stream/metadata_test.go
  banyand/tsdb/bucket/queue_test.go
  banyand/tsdb/bucket/strategy_test.go
  banyand/tsdb/shard_test.go
  bydbctl/internal/cmd/group_test.go
  bydbctl/internal/cmd/index_rule_binding_test.go
  bydbctl/internal/cmd/index_rule_test.go
  bydbctl/internal/cmd/measure_test.go
  bydbctl/internal/cmd/property_test.go
  bydbctl/internal/cmd/stream_test.go
  pkg/flow/streaming/flow_sliding_window_test.go
  pkg/flow/streaming/flow_test.go
  test/cases/measure/data/data.go
  test/cases/measure/measure.go
  test/cases/stream/data/data.go
  test/cases/stream/stream.go
  test/cases/topn/topn.go
  test/integration/other/measure_test.go
  test/integration/other/tls_test.go
Labels: testing

#214 Fix stream's leaked goroutines
  banyand/metadata/schema/etcd.go
  banyand/queue/local.go
  banyand/queue/queue.go
  banyand/stream/metadata_test.go
  banyand/tsdb/index/writer.go
  pkg/bus/bus.go
Labels: bug

#216 Correct doc about the CLI config file
  docs/clients.md
Labels: documentation

#217 Move group as the first doc of concepts
  docs/menu.yml
Labels: documentation

#218 Move group as the first doc of concepts
  docs/concept/data-model.md
Labels: documentation

#220 Fix some flaws in kv
  banyand/kv/badger.go
  banyand/kv/kv.go
  banyand/measure/measure_query.go
  banyand/tsdb/block.go
  banyand/tsdb/series.go
  banyand/tsdb/series_seek.go
  banyand/tsdb/series_seek_sort.go
  pkg/encoding/encoding.go
  pkg/encoding/int.go
  pkg/encoding/int_test.go
  pkg/encoding/plain.go
  pkg/index/iterator.go
  pkg/pb/v1/write.go
  pkg/query/logical/measure/measure_plan_indexscan_local.go
Labels: bug, chore
