Repository apache/skywalking-banyandb, pull requests merged in 2022-02, with the labels that each got.

#77 Remove unnecessary PATH usage in Makefile(s)
  api/Makefile
  scripts/build/generate_go.mk
Labels: enhancement

#79 Add a queue to track and close blocks
  banyand/tsdb/block.go
  banyand/tsdb/bucket/bucket.go
  banyand/tsdb/bucket/queue.go
  banyand/tsdb/bucket/queue_test.go
  banyand/tsdb/bucket/strategy.go
  banyand/tsdb/bucket/strategy_test.go
  banyand/tsdb/segment.go
  banyand/tsdb/shard.go
  banyand/tsdb/shard_test.go
  banyand/tsdb/tsdb.go
  go.mod
  go.sum
  pkg/timestamp/range.go
Labels: enhancement

#82 Reopen closed blocks on touching
  banyand/stream/stream_query.go
  banyand/tsdb/block.go
  banyand/tsdb/segment.go
  banyand/tsdb/seriesdb.go
  banyand/tsdb/shard.go
  banyand/tsdb/shard_test.go
  banyand/tsdb/tsdb.go
  go.mod
Labels: enhancement

#83 Increase the timeout of block tests
  banyand/tsdb/shard_test.go
Labels: bug

#84 Fix the index iterator overflow
  banyand/stream/stream_write.go
  banyand/tsdb/block.go
  banyand/tsdb/segment.go
  banyand/tsdb/series_write.go
  banyand/tsdb/seriesdb.go
  banyand/tsdb/shard.go
  go.mod
  pkg/index/inverted/inverted.go
  pkg/index/iterator.go
  pkg/index/lsm/lsm.go
  pkg/index/lsm/search.go
  pkg/query/logical/common.go
  pkg/run/run.go
Labels: bug

#85 Move metadata event handler to the pkg package
  banyand/stream/metadata.go
  banyand/stream/metadata_test.go
  banyand/stream/service.go
  banyand/stream/stream.go
  pkg/pb/v1/metadata.go
  pkg/schema/metadata.go
Labels: enhancement

#87 Add groupBy to the measure query request
  api/proto/banyandb/measure/v1/query.pb.go
  api/proto/banyandb/measure/v1/query.proto
  api/proto/banyandb/measure/v1/topn.pb.go
  api/proto/banyandb/measure/v1/topn.proto
  api/proto/banyandb/model/v1/common.pb.go
  api/proto/banyandb/model/v1/common.proto
Labels: api
