Repository apache/skywalking-banyandb, pull requests merged in 2022-10, with the labels that each got.

#181 Refactor Property
  api/proto/banyandb/property/v1/rpc.pb.go
  api/proto/banyandb/property/v1/rpc.pb.gw.go
  api/proto/banyandb/property/v1/rpc.pb.validate.go
  api/proto/banyandb/property/v1/rpc.proto
  api/proto/banyandb/property/v1/rpc_grpc.pb.go
  api/proto/openapi/banyandb/property/v1/rpc.swagger.json
  banyand/liaison/grpc/property.go
  banyand/metadata/schema/property.go
  banyand/metadata/schema/schema.go
  docs/api-reference.md
  test/integration/other/property_test.go
Labels: enhancement, api

#183 Fix test cases with Eventually semantics
  pkg/query/logical/measure/measure_plan_indexscan_local.go
  test/cases/measure/data/data.go
  test/cases/measure/measure.go
  test/cases/stream/stream.go
  test/integration/cold_query/query_suite_test.go
  test/integration/other/measure_test.go
  test/integration/other/other_suite_test.go
  test/integration/other/tls_test.go
  test/integration/query/query_suite_test.go
Labels: testing

#185 Make import order deterministic
  .golangci-format.yml
  .golangci.yml
  banyand/liaison/grpc/registry_test.go
  banyand/stream/metadata.go
  banyand/tsdb/block.go
  banyand/tsdb/retention.go
  banyand/tsdb/segment.go
  bydbctl/internal/cmd/group.go
  bydbctl/internal/cmd/root.go
  bydbctl/internal/cmd/stream.go
  bydbctl/internal/cmd/stream_test.go
  bydbctl/internal/cmd/use.go
  deprecated-golangci.yml
  pkg/index/lsm/lsm.go
  pkg/query/logical/index_filter.go
  pkg/query/logical/measure/schema.go
  pkg/query/logical/tag_filter.go
  pkg/signal/handler.go
  pkg/test/setup/setup.go
  pkg/test/stream/traffic/traffic.go
  pkg/timestamp/nano.go
  scripts/build/lint-bin.mk
  test/integration/other/property_test.go
Labels: chore

#186 Add Exist endpoints to all services
  api/proto/banyandb/database/v1/rpc.pb.go
  api/proto/banyandb/database/v1/rpc.pb.validate.go
  api/proto/banyandb/database/v1/rpc.proto
  api/proto/banyandb/database/v1/rpc_grpc.pb.go
  api/proto/openapi/banyandb/database/v1/rpc.swagger.json
  banyand/liaison/grpc/registry.go
  banyand/liaison/grpc/registry_test.go
  docs/api-reference.md
Labels: api

#187 Try to create the group if absent
  pkg/schema/metadata.go
Labels: bug

#188 Fix having semantic inconsistency
  pkg/query/logical/common.go
  pkg/query/logical/expr_literal.go
  pkg/query/logical/index_filter.go
  pkg/query/logical/interface.go
  pkg/query/logical/stream/stream_plan_tag_filter.go
  pkg/query/logical/tag_filter.go
  pkg/test/stream/testdata/stream.json
  test/cases/stream/data/input/having_non_indexed.yaml
  test/cases/stream/data/input/having_non_indexed_arr.yaml
  test/cases/stream/data/testdata/data.json
  test/cases/stream/data/want/having_non_indexed.yaml
  test/cases/stream/data/want/having_non_indexed_arr.yaml
  test/cases/stream/stream.go
Labels: bug

#189 Fixes some issues found by Java client updating
  banyand/liaison/grpc/server.go
  banyand/liaison/http/server.go
  banyand/tsdb/index/writer.go
  bydbctl/internal/cmd/cmd_suite_test.go
  pkg/partition/index.go
  pkg/query/logical/common.go
  pkg/query/logical/index_filter.go
  pkg/query/logical/tag_filter.go
  pkg/schema/metadata.go
  test/cases/stream/data/data.go
  test/cases/stream/data/input/global_index.yaml
  test/cases/stream/stream.go
Labels: bug, chore

#196 Add more data points to flush topn results
  bydbctl/internal/cmd/measure_test.go
  pkg/test/helpers/http_health.go
  test/cases/measure/data/data.go
  test/cases/measure/data/testdata/service_cpm_minute_data2.json
  test/cases/measure/measure.go
  test/cases/topn/data/want/desc.yaml
  test/cases/topn/topn.go
  test/integration/cold_query/query_suite_test.go
  test/integration/query/query_suite_test.go
Labels: testing

#195 Add bydbctl's examples
  api/proto/banyandb/common/v1/common.pb.go
  api/proto/banyandb/common/v1/common.pb.validate.go
  api/proto/banyandb/common/v1/common.proto
  bydbctl/README.md
  docs/clients.md
  docs/crud/group.md
  docs/crud/index_rule.md
  docs/crud/index_rule_binding.md
  docs/crud/measure/query.md
  docs/crud/measure/schema.md
  docs/crud/measure/write.md
  docs/crud/property.md
  docs/crud/property/create.md
  docs/crud/property/delete.md
  docs/crud/property/query.md
  docs/crud/property/update.md
  docs/crud/stream/query.md
  docs/crud/stream/schema.md
  docs/crud/stream/write.md
  docs/installation.md
  docs/menu.yml
Labels: documentation

#201 Fix flaky test cases
  banyand/measure/measure_topn.go
  banyand/measure/measure_write.go
  banyand/measure/service.go
  bydbctl/internal/cmd/index_rule_binding_test.go
  bydbctl/internal/cmd/index_rule_test.go
  bydbctl/internal/cmd/measure_test.go
  bydbctl/internal/cmd/rest.go
  bydbctl/internal/cmd/stream_test.go
  test/integration/cold_query/query_suite_test.go
  test/integration/query/query_suite_test.go
Labels: testing
