Repository apache/skywalking-banyandb, pull requests merged in 2022-09, with the labels that each got.

#169 Fix data race
  pkg/schema/metadata.go
Labels: bug

#173 Bump up api plugins
  api/proto/buf.lock
  api/proto/buf.yaml
Labels: api, chore

#174 Update official doc path
  README.md
Labels: documentation

#175 Stream and measure schema management
  dist/LICENSE
  dist/licenses/ui-licenses/license-asynckit.txt
  dist/licenses/ui-licenses/license-axios.txt
  dist/licenses/ui-licenses/license-combined-stream.txt
  dist/licenses/ui-licenses/license-delayed-stream.txt
  dist/licenses/ui-licenses/license-follow-redirects.txt
  dist/licenses/ui-licenses/license-form-data.txt
  dist/licenses/ui-licenses/license-mime-db.txt
  dist/licenses/ui-licenses/license-mime-types.txt
  dist/licenses/ui-licenses/license-picocolors.txt
  dist/licenses/ui-licenses/license-postcss.txt
  dist/licenses/ui-licenses/license-vue-cli-plugin-axios.txt
  ui/.browserslistrc
  ui/LICENSE
  ui/README.md
  ui/jsconfig.json
  ui/package-lock.json
  ui/package.json
  ui/src/App.vue
  ui/src/api/index.js
  ui/src/components/HeaderComponent.vue
  ui/src/components/databaseComponents/MainComponent.vue
  ui/src/components/databaseComponents/TagNavigationComponent.vue
  ui/src/components/databaseComponents/asideComponents/AsideComponent.vue
  ui/src/components/databaseComponents/asideComponents/DialogResourcesComponent.vue
  ui/src/components/databaseComponents/asideComponents/RightMenuComponent.vue
  ui/src/components/databaseComponents/asideComponents/RightMenuItemComponent.vue
  ui/src/components/databaseComponents/mainComponents/DataTableComponent.vue
  ui/src/components/databaseComponents/mainComponents/DrawerRightComponent.vue
  ui/src/components/databaseComponents/mainComponents/SecondNavigationComponent.vue
  ui/src/components/databaseComponents/mainComponents/drawerRightComponents/DetailListComponent.vue
  ui/src/components/databaseComponents/mainComponents/drawerRightComponents/DetailTableComponent.vue
  ui/src/main.js
  ui/src/store/menuState.js
  ui/src/store/tags.js
  ui/src/utils/axios.js
Labels: ui

#176 Add segment interval options
  api/proto/banyandb/common/v1/common.pb.go
  api/proto/banyandb/common/v1/common.pb.validate.go
  api/proto/banyandb/common/v1/common.proto
  api/proto/openapi/banyandb/database/v1/rpc.swagger.json
  banyand/measure/metadata.go
  banyand/metadata/schema/testdata/group.json
  banyand/stream/metadata.go
  banyand/tsdb/tsdb.go
  banyand/tsdb/tsdb_test.go
  bydbctl/internal/cmd/group.go
  bydbctl/internal/cmd/stream_test.go
  docs/api-reference.md
  pkg/pb/v1/metadata.go
  pkg/test/measure/testdata/groups/sw_metric.json
  pkg/test/stream/testdata/group.json
Labels: api

#177 Introduce two key feats to tsdb
  banyand/measure/measure_write.go
  banyand/measure/metadata.go
  banyand/stream/metadata.go
  banyand/stream/stream_write.go
  banyand/tsdb/block.go
  banyand/tsdb/bucket/queue.go
  banyand/tsdb/retention.go
  banyand/tsdb/segment.go
  banyand/tsdb/series.go
  banyand/tsdb/seriesdb.go
  banyand/tsdb/shard.go
  banyand/tsdb/shard_test.go
  banyand/tsdb/tsdb.go
  banyand/tsdb/tsdb_test.go
  dist/LICENSE
  dist/licenses/license-github.com-robfig-cron-v3.txt
  go.mod
  go.sum
  test/integration/cold_query/query_suite_test.go
Labels: enhancement
