Repository apache/skywalking-banyandb, pull requests merged in 2022-06, with the labels that each got.

#124 Add release script and document
  .gitignore
  Makefile
  README.md
  docs/release.md
  scripts/release.sh
  target/golist.json
Labels: documentation

#125 Build binary from sources package
  Makefile
  docs/release.md
  scripts/build/build.mk
  scripts/release.sh
Labels: documentation

#131 Add roadmap
  README.md
Labels: documentation

#132 Do some chores
  .github/workflows/e2e.storage.yml
  .github/workflows/go.yml
  .github/workflows/publish-docker.yml
  .golangci.yml
  .licenserc.yaml
  Makefile
  api/Makefile
  api/common/id.go
  banyand/Makefile
  bydbctl/internal/cmd/root.go
  bydbctl/internal/cmd/root_test.go
  desperated-golangci.yml
  dist/LICENSE
  dist/licenses/ui-licenses/license-bindings.txt
  dist/licenses/ui-licenses/license-file-uri-to-path.txt
  dist/licenses/ui-licenses/license-nan.txt
  pkg/Makefile
  revive.toml
  scripts/build/license.mk
  scripts/build/lint.mk
  ui/.gitignore
  ui/.licenserc.yaml
  ui/LICENSE
  ui/Makefile
  ui/README.md
  ui/package.json
  ui/tools/checkversion.js
Labels: chore

#135 Add grpc-gateway
  .golangci-format.yml
  .licenserc.yaml
  Makefile
  api/Makefile
  api/buf.gen.yaml
  api/proto/banyandb/database/v1/rpc.pb.go
  api/proto/banyandb/database/v1/rpc.pb.gw.go
  api/proto/banyandb/database/v1/rpc.proto
  api/proto/banyandb/measure/v1/rpc.pb.go
  api/proto/banyandb/measure/v1/rpc.pb.gw.go
  api/proto/banyandb/measure/v1/rpc.proto
  api/proto/banyandb/property/v1/rpc.pb.go
  api/proto/banyandb/property/v1/rpc.pb.gw.go
  api/proto/banyandb/property/v1/rpc.proto
  api/proto/banyandb/stream/v1/rpc.pb.go
  api/proto/banyandb/stream/v1/rpc.pb.gw.go
  api/proto/banyandb/stream/v1/rpc.proto
  api/proto/buf.lock
  api/proto/buf.yaml
  api/proto/openapi/banyandb/common/v1/common.swagger.json
  api/proto/openapi/banyandb/database/v1/database.swagger.json
  api/proto/openapi/banyandb/database/v1/event.swagger.json
  api/proto/openapi/banyandb/database/v1/rpc.swagger.json
  api/proto/openapi/banyandb/database/v1/schema.swagger.json
  api/proto/openapi/banyandb/measure/v1/query.swagger.json
  api/proto/openapi/banyandb/measure/v1/rpc.swagger.json
  api/proto/openapi/banyandb/measure/v1/topn.swagger.json
  api/proto/openapi/banyandb/measure/v1/write.swagger.json
  api/proto/openapi/banyandb/model/v1/common.swagger.json
  api/proto/openapi/banyandb/model/v1/query.swagger.json
  api/proto/openapi/banyandb/property/v1/property.swagger.json
  api/proto/openapi/banyandb/property/v1/rpc.swagger.json
  api/proto/openapi/banyandb/stream/v1/query.swagger.json
  api/proto/openapi/banyandb/stream/v1/rpc.swagger.json
  api/proto/openapi/banyandb/stream/v1/write.swagger.json
  banyand/liaison/http/server.go
  dist/LICENSE
  dist/licenses/license-github.com-go-chi-chi-v5.txt
  dist/licenses/license-github.com-grpc-ecosystem-grpc-gateway-v2.txt
  go.mod
  go.sum
  ui/.gitignore
  ui/.licenserc.yaml
  ui/Makefile
Labels: enhancement

#141 Bump up skywalking-eye
  dist/LICENSE
  dist/licenses/ui-licenses/license-bindings.txt
  dist/licenses/ui-licenses/license-file-uri-to-path.txt
  dist/licenses/ui-licenses/license-nan.txt
  scripts/build/license.mk
  ui/LICENSE
Labels: bug
