Repository apache/skywalking-banyandb, pull requests merged in 2022-05, with the labels that each got.

#110 Introduce gorilla encoder to measure
  .gitignore
  api/proto/banyandb/database/v1/schema.pb.go
  api/proto/banyandb/database/v1/schema.proto
  banyand/liaison/grpc/measure_test.go
  banyand/liaison/grpc/stream_test.go
  banyand/measure/encode.go
  banyand/measure/field_flag_test.go
  banyand/measure/measure.go
  banyand/measure/measure_query.go
  banyand/measure/measure_write.go
  banyand/measure/metadata.go
  banyand/stream/stream_query.go
  banyand/stream/stream_write.go
  banyand/tsdb/series_seek.go
  banyand/tsdb/series_write.go
  banyand/tsdb/seriesdb.go
  banyand/tsdb/seriesdb_test.go
  pkg/bit/writer.go
  pkg/encoding/int.go
  pkg/encoding/int_test.go
  pkg/encoding/plain.go
  pkg/test/measure/testdata/measures/service_cpm_day.json
  pkg/test/measure/testdata/measures/service_instance_cpm_day.json
  pkg/timestamp/duration.go
  pkg/timestamp/duration_test.go
Labels: enhancement

#111 Add docs
  README.md
  api/Makefile
  api/buf.gen.yaml
  banyand/internal/cmd/standalone.go
  banyand/liaison/grpc/server.go
  docs/README.md
  docs/api-reference.md
  docs/clients.md
  docs/crud/measure/query.md
  docs/crud/measure/write.md
  docs/crud/property/create.md
  docs/crud/property/delete.md
  docs/crud/property/query.md
  docs/crud/property/update.md
  docs/crud/stream/query.md
  docs/crud/stream/write.md
  docs/installation.md
  docs/menu.yml
  docs/schema.md
  scripts/build/base.mk
Labels: documentation

#112 Fix UT failures under a non-UTC timezone
  .github/workflows/go.yml
  banyand/liaison/grpc/grpc_suite_test.go
  banyand/measure/measure_suite_test.go
  banyand/metadata/metadata.go
  banyand/metadata/metadata_test.go
  banyand/metadata/schema/etcd.go
  banyand/metadata/schema/etcd_test.go
  banyand/metadata/schema/schema_suite_test.go
  banyand/query/processor_test.go
  banyand/stream/stream_suite_test.go
  banyand/tsdb/bucket/bucket_suite_test.go
  banyand/tsdb/segment.go
  banyand/tsdb/shard_test.go
  banyand/tsdb/tsdb_suite_test.go
  go.mod
  go.sum
  pkg/bus/bus.go
  pkg/bus/bus_test.go
  pkg/index/inverted/inverted_test.go
  pkg/index/lsm/lsm_test.go
  pkg/query/logical/common_test.go
  pkg/query/logical/measure_analyzer_test.go
  pkg/timestamp/clock.go
  scripts/build/test.mk
Labels: bug

#113 Set doc link to host docs
  README.md
Labels: documentation

#114 Correct the behaviour of group by
  banyand/query/processor.go
  pkg/query/logical/measure_plan_execution_test.go
Labels: bug

#115 Fix the updating failure of the measure
  banyand/measure/measure_query.go
  banyand/measure/measure_query_test.go
  banyand/measure/measure_write.go
  banyand/measure/measure_write_test.go
Labels: bug

#116 Fix data race of ob apis
  pkg/index/inverted/field_map.go
  pkg/index/inverted/term_map.go
Labels: bug

#117 Enhance the measure query
  api/proto/banyandb/measure/v1/query.pb.go
  api/proto/banyandb/measure/v1/query.proto
  banyand/liaison/grpc/measure.go
  banyand/liaison/grpc/stream.go
  docs/api-reference.md
  pkg/pb/v1/query.go
  pkg/query/logical/measure_analyzer.go
  pkg/query/logical/measure_analyzer_test.go
  pkg/query/logical/measure_plan.go
  pkg/query/logical/measure_plan_execution_test.go
  pkg/query/logical/measure_plan_indexscan_local.go
  pkg/timestamp/nano.go
Labels: enhancement

#118 Fix timeRange check
  banyand/liaison/grpc/stream.go
Labels: bug

#119 Fix invalid default time range
  banyand/liaison/grpc/stream.go
  pkg/timestamp/nano.go
  pkg/timestamp/nano_test.go
Labels: bug

#120 Fix several issues of querying
  banyand/metadata/metadata_test.go
  banyand/stream/stream_query_test.go
  banyand/stream/stream_write_test.go
  banyand/stream/testdata/multiple_shards.json
  banyand/tsdb/index/writer.go
  pkg/bus/bus_test.go
  pkg/index/tree.go
  pkg/pb/v1/write.go
  pkg/query/logical/expr.go
  pkg/query/logical/expr_literal.go
  pkg/query/logical/interface.go
  pkg/query/logical/stream_analyzer.go
  pkg/query/logical/stream_analyzer_test.go
  pkg/query/logical/stream_plan_execution_test.go
  pkg/query/logical/stream_plan_indexscan_global.go
  pkg/query/logical/stream_plan_indexscan_local.go
  pkg/query/logical/stream_plan_tag_filter.go
  pkg/query/logical/testdata/global_index.json
  pkg/test/stream/testdata/index_rule_binding.json
  pkg/test/stream/testdata/index_rules/extended_tags.json
  pkg/test/stream/testdata/stream.json
Labels: bug, enhancement

#121 Rearrage the result of topN
  pkg/query/logical/measure_plan_execution_test.go
  pkg/query/logical/measure_plan_top.go
Labels: bug

#81 Add OAP E2E test case
  .github/workflows/e2e.storage.yml
  .licenserc.yaml
  test/e2e-v2/cases/event/banyandb/docker-compose.yml
  test/e2e-v2/cases/event/banyandb/e2e.yaml
  test/e2e-v2/cases/event/event-cases.yaml
  test/e2e-v2/cases/event/expected/events.yml
  test/e2e-v2/cases/event/expected/report-event.yml
  test/e2e-v2/cases/profiling/ebpf/Dockerfile.sqrt
  test/e2e-v2/cases/profiling/ebpf/banyandb/docker-compose.yml
  test/e2e-v2/cases/profiling/ebpf/banyandb/e2e.yaml
  test/e2e-v2/cases/profiling/ebpf/docker-compose.yml
  test/e2e-v2/cases/profiling/ebpf/expected/instance.yml
  test/e2e-v2/cases/profiling/ebpf/expected/process-estimate-scale.yml
  test/e2e-v2/cases/profiling/ebpf/expected/process.yml
  test/e2e-v2/cases/profiling/ebpf/expected/profiling-analysis.yml
  test/e2e-v2/cases/profiling/ebpf/expected/profiling-create-prepare.yml
  test/e2e-v2/cases/profiling/ebpf/expected/profiling-create.yml
  test/e2e-v2/cases/profiling/ebpf/expected/profiling-schedule-list.yml
  test/e2e-v2/cases/profiling/ebpf/expected/profiling-task-list.yml
  test/e2e-v2/cases/profiling/ebpf/expected/service.yml
  test/e2e-v2/cases/profiling/ebpf/profiling-cases.yaml
  test/e2e-v2/cases/profiling/ebpf/sqrt.go
  test/e2e-v2/cases/profiling/trace/banyandb/docker-compose.yml
  test/e2e-v2/cases/profiling/trace/banyandb/e2e.yaml
  test/e2e-v2/cases/profiling/trace/expected/profile-create.yml
  test/e2e-v2/cases/profiling/trace/expected/profile-list-finished.yml
  test/e2e-v2/cases/profiling/trace/expected/profile-list-notified.yml
  test/e2e-v2/cases/profiling/trace/expected/profile-segment-analyze.yml
  test/e2e-v2/cases/profiling/trace/expected/profile-segment-detail.yml
  test/e2e-v2/cases/profiling/trace/expected/profile-segment-list.yml
  test/e2e-v2/cases/profiling/trace/expected/service-endpoint.yml
  test/e2e-v2/cases/profiling/trace/expected/service-instance.yml
  test/e2e-v2/cases/profiling/trace/expected/service.yml
  test/e2e-v2/cases/profiling/trace/expected/traces-list.yml
  test/e2e-v2/cases/profiling/trace/profiling-cases.yaml
  test/e2e-v2/cases/storage/banyandb/docker-compose.yml
  test/e2e-v2/cases/storage/banyandb/e2e.yaml
  test/e2e-v2/cases/storage/expected/dependency-services.yml
  test/e2e-v2/cases/storage/expected/event-list.yml
  test/e2e-v2/cases/storage/expected/layer.yml
  test/e2e-v2/cases/storage/expected/metrics-has-value.yml
  test/e2e-v2/cases/storage/expected/metrics-top-service-sla.yml
  test/e2e-v2/cases/storage/expected/service-endpoint.yml
  test/e2e-v2/cases/storage/expected/service-instance.yml
  test/e2e-v2/cases/storage/expected/service.yml
  test/e2e-v2/cases/storage/expected/trace-info-detail.yml
  test/e2e-v2/cases/storage/expected/trace-users-detail.yml
  test/e2e-v2/cases/storage/expected/traces-list.yml
  test/e2e-v2/cases/storage/storage-cases.yaml
  test/e2e-v2/script/docker-compose/base-compose.yml
  test/e2e-v2/script/env
  test/e2e-v2/script/prepare/setup-e2e-shell/install-swctl.sh
  test/e2e-v2/script/prepare/setup-e2e-shell/install-yq.sh
  test/e2e-v2/script/prepare/setup-e2e-shell/install.sh
  test/e2e-v2/script/prepare/setup-oap/log4j2.xml
Labels: testing

#122 Add the stress test framework
  banyand/internal/cmd/standalone.go
  banyand/liaison/grpc/measure.go
  banyand/liaison/grpc/measure_test.go
  banyand/liaison/grpc/server.go
  banyand/liaison/grpc/stream.go
  banyand/liaison/grpc/stream_test.go
  banyand/measure/encode.go
  banyand/measure/measure.go
  banyand/measure/measure_suite_test.go
  banyand/measure/metadata.go
  banyand/tsdb/block.go
  banyand/tsdb/metric.go
  pkg/encoding/encoding.go
  pkg/encoding/int.go
  pkg/encoding/plain.go
  pkg/grpchelper/client.go
  pkg/logger/logger.go
  pkg/logger/setting.go
  pkg/test/helpers/fail_interceptor.go
  pkg/test/helpers/grpc_health.go
  pkg/test/measure/etcd.go
  pkg/test/measure/testdata/measures/service_cpm_day.json
  pkg/test/measure/traffic/traffic.go
  pkg/test/stream/etcd.go
  pkg/test/stream/traffic/traffic.go
  pkg/test/stream/traffic/traffic_test.go
  scripts/build/base.mk
  scripts/build/test.mk
  target/golist.json
  test/cases/stream_tests/templates/searchable_template.json
  test/cases/stream_tests/write.go
  test/stress/stress_suite_test.go
Labels: testing
