Repository apache/skywalking-banyandb, pull requests merged in 2022-04, with the labels that each got.

#96 Improve the observability of banyandb
  api/common/id.go
  banyand/internal/cmd/standalone.go
  banyand/kv/badger.go
  banyand/kv/kv.go
  banyand/measure/metadata.go
  banyand/observability/metric.go
  banyand/observability/pprof.go
  banyand/observability/type.go
  banyand/stream/metadata.go
  banyand/tsdb/block.go
  banyand/tsdb/index/writer.go
  banyand/tsdb/metric.go
  banyand/tsdb/scope.go
  banyand/tsdb/segment.go
  banyand/tsdb/seriesdb.go
  banyand/tsdb/shard.go
  go.mod
  go.sum
  pkg/index/index.go
  pkg/index/inverted/field_map.go
  pkg/index/inverted/inverted.go
  pkg/index/inverted/mem.go
  pkg/index/inverted/term_map.go
  pkg/index/lsm/lsm.go
  pkg/index/posting/posting.go
  pkg/index/posting/roaring/roaring.go
  pkg/test/stream/traffic/searchable_template.json
  pkg/test/stream/traffic/traffic_test.go
Labels: enhancement

#97 Fix NPE of stating badger kv
  banyand/tsdb/block.go
  banyand/tsdb/metric.go
  go.mod
  go.sum
Labels: bug

#98 Uncomment measure
  banyand/liaison/grpc/server.go
Labels: bug

#101 Fix duplicate datapoints
  api/proto/banyandb/measure/v1/query.pb.go
  api/proto/banyandb/measure/v1/query.proto
  api/proto/banyandb/measure/v1/topn.pb.go
  api/proto/banyandb/measure/v1/topn.proto
  api/proto/banyandb/measure/v1/write.pb.go
  api/proto/banyandb/measure/v1/write.proto
  api/proto/banyandb/stream/v1/query.pb.go
  api/proto/banyandb/stream/v1/query.proto
  api/proto/banyandb/stream/v1/write.pb.go
  api/proto/banyandb/stream/v1/write.proto
  banyand/measure/measure_write.go
  banyand/measure/measure_write_test.go
  banyand/query/processor_test.go
  banyand/stream/stream_query_test.go
  banyand/stream/stream_write.go
  banyand/stream/stream_write_test.go
  banyand/tsdb/metric.go
  pkg/query/logical/common_test.go
  pkg/timestamp/nano.go
  pkg/timestamp/nano_test.go
Labels: bug

#100 Return error created from status
  banyand/liaison/grpc/property.go
  banyand/liaison/grpc/registry.go
  banyand/liaison/grpc/registry_test.go
  banyand/metadata/schema/error.go
  banyand/metadata/schema/etcd.go
  banyand/metadata/schema/etcd_test.go
  banyand/metadata/schema/group.go
  banyand/metadata/schema/index.go
  banyand/metadata/schema/measure.go
  banyand/metadata/schema/property.go
  banyand/metadata/schema/schema.go
  banyand/metadata/schema/stream.go
  banyand/metadata/schema/topn.go
  go.mod
  pkg/test/measure/etcd.go
  pkg/test/stream/etcd.go
Labels: api

#102 Trigger inverted index flushing on flushing the main store
  banyand/kv/kv.go
  banyand/tsdb/block.go
  pkg/index/index.go
  pkg/index/lsm/lsm.go
Labels: bug

#103 Add test cases for verifying numeric values of the inverted index
  banyand/metadata/schema/testdata/stream.json
  banyand/query/processor_test.go
  banyand/query/testdata/global_index.json
  banyand/query/testdata/multiple_shards.json
  banyand/stream/stream_query_test.go
  banyand/stream/testdata/global_index.json
  banyand/stream/testdata/multiple_shards.json
  pkg/query/logical/testdata/global_index.json
  pkg/query/logical/testdata/multiple_shards.json
  pkg/test/stream/testdata/stream.json
Labels: bug

#104 Make sure index rule ID is set by
  banyand/liaison/grpc/grpc_suite_test.go
  banyand/liaison/grpc/measure_test.go
  banyand/liaison/grpc/stream_test.go
  banyand/metadata/schema/error.go
  banyand/metadata/schema/index.go
  banyand/tsdb/shard_test.go
  pkg/schema/metadata.go
Labels: bug

#106 Introduce the clock mock to test block controller
  banyand/tsdb/block.go
  banyand/tsdb/bucket/bucket.go
  banyand/tsdb/bucket/queue.go
  banyand/tsdb/bucket/strategy.go
  banyand/tsdb/segment.go
  banyand/tsdb/shard.go
  banyand/tsdb/shard_test.go
  banyand/tsdb/tsdb.go
  go.mod
  go.sum
  pkg/timestamp/clock.go
Labels: bug

#107 Increase time range to fix flaky testing
  banyand/liaison/grpc/measure_test.go
  banyand/liaison/grpc/stream_test.go
Labels: bug, testing

#108 Check input time range
  banyand/liaison/grpc/measure.go
  banyand/liaison/grpc/measure_test.go
  banyand/liaison/grpc/stream.go
  banyand/liaison/grpc/stream_test.go
  banyand/measure/measure_write.go
  banyand/stream/stream_write.go
  banyand/tsdb/shard_test.go
  banyand/tsdb/tsdb_suite_test.go
  pkg/timestamp/nano.go
Labels: bug

#109 Append group name to the end of tsdb's path
  banyand/measure/metadata.go
  banyand/stream/metadata.go
  pkg/schema/metadata.go
Labels: bug
