Repository apache/skywalking-banyandb, pull requests merged in 2022-08, with the labels that each got.

#150 Merge primary index into lsm index
  banyand/tsdb/block.go
  banyand/tsdb/metric.go
Labels: enhancement, testing

#152 Update go 1.19
  .github/workflows/e2e.storage.yml
  .github/workflows/go.yml
  .github/workflows/publish-docker.yml
  api/proto/banyandb/measure/v1/topn.pb.go
  api/proto/banyandb/measure/v1/write.pb.go
  api/proto/banyandb/model/v1/common.pb.go
  banyand/Dockerfile
  banyand/internal/cmd/root.go
  banyand/measure/encode.go
  banyand/measure/field_flag_test.go
  banyand/measure/measure_write_test.go
  banyand/measure/metadata.go
  banyand/observability/metric.go
  banyand/observability/type.go
  banyand/query/processor_test.go
  banyand/query/query_suite_test.go
  banyand/stream/stream_query_test.go
  banyand/tsdb/bucket/bucket_suite_test.go
  banyand/tsdb/bucket/queue.go
  banyand/tsdb/bucket/queue_test.go
  banyand/tsdb/bucket/strategy_test.go
  banyand/tsdb/metric.go
  banyand/tsdb/scope.go
  banyand/tsdb/series_test.go
  banyand/tsdb/shard_test.go
  banyand/tsdb/tsdb.go
  banyand/tsdb/tsdb_suite_test.go
  bydbctl/Dockerfile
  bydbctl/cmd/bydbctl/main.go
  bydbctl/internal/cmd/root.go
  go.mod
  pkg/grpchelper/client.go
  pkg/query/aggregation/aggregation.go
  pkg/query/aggregation/function.go
  pkg/query/logical/common_test.go
  pkg/query/logical/iter.go
  pkg/query/logical/measure_plan_aggregation.go
  pkg/query/logical/measure_plan_groupby.go
  pkg/query/logical/measure_plan_top.go
  pkg/query/logical/measure_top.go
  pkg/query/logical/measure_top_test.go
  pkg/query/logical/stream_analyzer.go
  pkg/run/run.go
  pkg/test/helpers/fail_interceptor.go
  pkg/test/helpers/grpc_health.go
  pkg/test/matcher.go
  pkg/test/measure/traffic/traffic.go
  pkg/test/space.go
  pkg/test/stream/traffic/traffic.go
  pkg/timestamp/clock.go
  pkg/timestamp/duration.go
  pkg/timestamp/duration_test.go
  pkg/timestamp/nano.go
  pkg/timestamp/nano_test.go
  pkg/timestamp/range.go
  scripts/build/lint-bin.mk
  scripts/ci/check/version_test.go
  ui/embed.go
Labels: dependencies

#153 Parameterize memory size and some key improvements
  Makefile
  banyand/kv/kv.go
  banyand/measure/metadata.go
  banyand/measure/service.go
  banyand/stream/metadata.go
  banyand/stream/service.go
  banyand/stream/stream.go
  banyand/tsdb/block.go
  banyand/tsdb/bucket/strategy.go
  banyand/tsdb/bucket/strategy_test.go
  banyand/tsdb/index/writer.go
  banyand/tsdb/metric.go
  banyand/tsdb/segment.go
  banyand/tsdb/series.go
  banyand/tsdb/seriesdb.go
  banyand/tsdb/shard.go
  banyand/tsdb/shard_test.go
  banyand/tsdb/tsdb.go
  banyand/tsdb/tsdb_suite_test.go
  dist/LICENSE
  go.mod
  go.sum
  pkg/index/index.go
  pkg/index/lsm/lsm.go
  pkg/run/channel.go
  pkg/test/helpers/fail_interceptor.go
  pkg/timestamp/clock.go
Labels: enhancement

#154 Fix tsdb's leaked goroutines
  banyand/tsdb/block.go
  banyand/tsdb/bucket/bucket.go
  banyand/tsdb/bucket/queue_test.go
  banyand/tsdb/bucket/strategy.go
  banyand/tsdb/bucket/strategy_test.go
  banyand/tsdb/segment.go
  banyand/tsdb/shard_test.go
  dist/LICENSE
  go.mod
  go.sum
Labels: testing

#156 Add several metrics to measure the compression ratio
  banyand/kv/kv.go
  banyand/measure/encode.go
  banyand/measure/metadata.go
  banyand/query/processor.go
  banyand/stream/metadata.go
  banyand/stream/stream_write.go
  banyand/tsdb/block.go
  banyand/tsdb/tsdb_test.go
  dist/LICENSE
  go.mod
  go.sum
  pkg/encoding/encoding.go
  pkg/encoding/int.go
  pkg/encoding/int_test.go
  pkg/encoding/plain.go
  pkg/index/inverted/inverted.go
  pkg/index/inverted/mem.go
  test/stress/docker-compose.yaml
Labels: testing

#158 Fix data race
  banyand/tsdb/block.go
Labels: bug

#166 Introduce full text searching to stream and measure
  api/proto/banyandb/database/v1/schema.pb.go
  api/proto/banyandb/database/v1/schema.pb.validate.go
  api/proto/banyandb/database/v1/schema.proto
  api/proto/banyandb/model/v1/query.pb.go
  api/proto/banyandb/model/v1/query.proto
  api/proto/openapi/banyandb/database/v1/rpc.swagger.json
  api/proto/openapi/banyandb/measure/v1/rpc.swagger.json
  api/proto/openapi/banyandb/stream/v1/rpc.swagger.json
  banyand/tsdb/index/writer.go
  banyand/tsdb/series_seek.go
  banyand/tsdb/series_seek_filter.go
  docs/api-reference.md
  pkg/index/index.go
  pkg/index/inverted/inverted.go
  pkg/index/inverted/inverted_test.go
  pkg/index/lsm/search.go
  pkg/index/testcases/duration.go
  pkg/index/tree.go
  pkg/pb/v1/query.go
  pkg/query/logical/common_test.go
  pkg/query/logical/expr.go
  pkg/query/logical/measure_analyzer_test.go
  pkg/query/logical/measure_plan_execution_test.go
  pkg/query/logical/stream_analyzer_test.go
  pkg/query/logical/stream_plan_execution_test.go
  pkg/query/logical/testdata/measure_search_data.json
  pkg/query/logical/testdata/multiple_shards.json
  pkg/test/measure/testdata/index_rule_bindings/service_instance_traffic.json
  pkg/test/measure/testdata/index_rules/searchable_name.json
  pkg/test/stream/testdata/index_rules/db.instance.json
Labels: enhancement
