Repository apache/skywalking-banyandb, pull requests merged in 2023-08, with the labels that each got.

#310 Generate dependencies licenses in CI job
  .github/workflows/ci.yml
Labels: chore

#311 Drop discovery module
  CHANGES.md
  README.md
  api/event/doc.go
  api/event/measure.go
  api/event/stream.go
  api/proto/banyandb/database/v1/database.proto
  banyand/discovery/discovery.go
  banyand/internal/cmd/liaison.go
  banyand/internal/cmd/standalone.go
  banyand/internal/cmd/storage.go
  banyand/liaison/grpc/discovery.go
  banyand/liaison/grpc/registry_test.go
  banyand/liaison/grpc/server.go
  banyand/liaison/liaison.go
  banyand/measure/measure.go
  banyand/measure/measure_suite_test.go
  banyand/measure/metadata.go
  banyand/measure/metadata_test.go
  banyand/measure/service.go
  banyand/metadata/allocator.go
  banyand/metadata/client.go
  banyand/metadata/metadata.go
  banyand/metadata/schema/checker.go
  banyand/metadata/schema/node.go
  banyand/metadata/schema/schema.go
  banyand/metadata/schema/shard.go
  banyand/queue/local.go
  banyand/queue/queue.go
  banyand/stream/metadata.go
  banyand/stream/metadata_test.go
  banyand/stream/service.go
  banyand/stream/stream.go
  banyand/stream/stream_suite_test.go
  dist/LICENSE
  docs/api-reference.md
  go.mod
  go.sum
  pkg/schema/metadata.go
  pkg/test/setup/setup.go
Labels: enhancement, chore

#309 Add file system architecture doc
  assets/io_uring.jpg
  docs/concept/persistence-storage.md
Labels: documentation

#313 Support for recovery measure/buffer using wal
  CHANGES.md
  api/common/id.go
  banyand/measure/tstable.go
  banyand/stream/tstable.go
  banyand/tsdb/buffer.go
  banyand/tsdb/buffer_test.go
  pkg/convert/string.go
  pkg/wal/wal.go
  pkg/wal/wal_benchmark_test.go
  pkg/wal/wal_test.go
Labels: enhancement

#315 Update PULL_REQUEST_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE
Labels: chore

#314 Implement node role registration
  CHANGES.md
  api/common/id.go
  api/proto/banyandb/database/v1/database.proto
  api/proto/banyandb/database/v1/event.proto
  banyand/internal/cmd/liaison.go
  banyand/internal/cmd/meta.go
  banyand/internal/cmd/root.go
  banyand/internal/cmd/standalone.go
  banyand/internal/cmd/storage.go
  banyand/liaison/grpc/discovery.go
  banyand/liaison/grpc/registry_test.go
  banyand/liaison/grpc/server.go
  banyand/liaison/http/server.go
  banyand/liaison/liaison.go
  banyand/measure/measure_suite_test.go
  banyand/measure/metadata.go
  banyand/measure/service.go
  banyand/metadata/allocator.go
  banyand/metadata/client.go
  banyand/metadata/embeddedetcd/server.go
  banyand/metadata/metadata_test.go
  banyand/metadata/schema/checker.go
  banyand/metadata/schema/etcd.go
  banyand/metadata/schema/node.go
  banyand/metadata/schema/register_test.go
  banyand/metadata/schema/schema.go
  banyand/metadata/server.go
  banyand/query/processor.go
  banyand/stream/service.go
  banyand/stream/stream_suite_test.go
  docs/README.md
  docs/api-reference.md
  docs/concept/clustering.md
  docs/installation.md
  docs/installation/binaries.md
  docs/installation/cluster.md
  docs/installation/standalone.md
  docs/menu.yml
  pkg/host/host.go
  pkg/run/run.go
  pkg/schema/metadata.go
  pkg/signal/handler.go
  pkg/test/matcher.go
  pkg/test/measure/etcd.go
  pkg/test/setup.go
  pkg/test/setup/setup.go
  pkg/test/stream/etcd.go
  test/stress/cases/istio/repo.go
Labels: enhancement

#319 Add watcher to sync data in etcd to local cache
  CHANGES.md
  api/proto/banyandb/database/v1/database.proto
  banyand/liaison/grpc/discovery.go
  banyand/measure/metadata.go
  banyand/measure/service.go
  banyand/metadata/client.go
  banyand/metadata/metadata.go
  banyand/metadata/schema/etcd.go
  banyand/metadata/schema/etcd_test.go
  banyand/metadata/schema/group.go
  banyand/metadata/schema/index.go
  banyand/metadata/schema/kind.go
  banyand/metadata/schema/measure.go
  banyand/metadata/schema/node.go
  banyand/metadata/schema/property.go
  banyand/metadata/schema/register_test.go
  banyand/metadata/schema/schema.go
  banyand/metadata/schema/schema_suite_test.go
  banyand/metadata/schema/shard.go
  banyand/metadata/schema/stream.go
  banyand/metadata/schema/topn.go
  banyand/metadata/schema/watcher.go
  banyand/metadata/schema/watcher_test.go
  banyand/stream/metadata.go
  banyand/stream/service.go
  docs/api-reference.md
  go.mod
  pkg/logger/logger.go
  pkg/run/closer.go
  pkg/test/setup/setup.go
Labels: bug

#321 Refactor distributed query
  docs/concept/clustering.md
Labels: documentation
