Repository apache/skywalking-banyandb, pull requests merged in 2023-10, with the labels that each got.

#334 Add node selector to support topology calculation
  CHANGES.md
  banyand/liaison/grpc/node.go
  banyand/liaison/grpc/node_test.go
  banyand/queue/queue.go
  dist/LICENSE
  dist/licenses/license-github.com-dchest-siphash.txt
  dist/licenses/license-github.com-kkdai-maglev.txt
  go.mod
  go.sum
  pkg/cmdsetup/liaison.go
  pkg/node/interface.go
  pkg/node/maglev.go
  pkg/node/maglev_test.go
Labels: enhancement

#338 Fix testcase unstable state when tsdb/buffer is not closed
  banyand/tsdb/buffer_test.go
Labels: bug

#339 Shard-level buffer
  CHANGES.md
  banyand/kv/badger.go
  banyand/kv/badger_test.go
  banyand/kv/kv.go
  banyand/measure/tstable.go
  banyand/stream/tstable.go
  banyand/tsdb/block.go
  banyand/tsdb/buffer.go
  banyand/tsdb/buffer_test.go
  banyand/tsdb/shard.go
  banyand/tsdb/shard_test.go
  banyand/tsdb/tsdb.go
  banyand/tsdb/tsdb_test.go
  banyand/tsdb/tstable.go
Labels: enhancement

#344 Update doc for releasing v0.5.0
  README.md
  docs/installation.md
  docs/installation/cluster.md
  docs/observability.md
Labels: documentation

#345 Reset e2e back to main repo, fix the e2e settings
  .github/workflows/e2e.storage.yml
  test/docker/base-compose.yml
  test/e2e-v2/cases/cluster/docker-compose.yml
  test/e2e-v2/script/env
  test/stress/env
  test/stress/env.dev
Labels: testing

#331 Support etcd client authentication
  CHANGES.md
  banyand/metadata/client.go
  banyand/metadata/schema/etcd.go
  docs/installation/cluster.md
  go.mod
  test/integration/etcd/client_suite_test.go
  test/integration/etcd/client_test.go
  test/integration/etcd/testdata/ca.crt
  test/integration/etcd/testdata/client-clientusage.crt
  test/integration/etcd/testdata/client-clientusage.key.insecure
  test/integration/etcd/testdata/server-serverusage.crt
  test/integration/etcd/testdata/server-serverusage.key.insecure
  test/integration/etcd/testdata/server.crt
  test/integration/etcd/testdata/server.key.insecure
Labels: enhancement

#341 Implement local file system
  CHANGES.md
  docs/concept/persistence-storage.md
  pkg/fs/error.go
  pkg/fs/file_system.go
  pkg/fs/local_file_system.go
  pkg/fs/local_file_system_test.go
Labels: enhancement

#347 Fix the bug that property merge new tags failed
  CHANGES.md
  banyand/metadata/schema/property.go
  pkg/node/maglev_test.go
  test/integration/standalone/other/property_test.go
Labels: bug
