Repository apache/skywalking-banyandb, pull requests merged in 2023-02, with the labels that each got.

#246 Fix metadata-relevant bugs
  api/proto/banyandb/database/v1/schema.proto
  api/proto/banyandb/property/v1/property.proto
  banyand/metadata/schema/group.go
  banyand/metadata/schema/index.go
  banyand/metadata/schema/measure.go
  banyand/metadata/schema/property.go
  banyand/metadata/schema/stream.go
  banyand/metadata/schema/topn.go
  bydbctl/internal/cmd/index_rule_binding_test.go
  bydbctl/internal/cmd/index_rule_test.go
  bydbctl/internal/cmd/measure_test.go
  bydbctl/internal/cmd/property_test.go
  bydbctl/internal/cmd/stream_test.go
  docs/api-reference.md
  docs/concept/data-model.md
  test/integration/other/property_test.go
Labels: bug

#247 Update CHANGES.md
  CHANGES.md
Labels: documentation

#249 Write-ahead Logging design doc
  docs/concept/wal.md
Labels: documentation

#252 Adding support for editing streams
  ui/src/api/index.js
  ui/src/components2/StreamEditor/index.vue
  ui/src/components2/StreamEditor/tagEditor.vue
Labels: ui

#251 Fix the broken of schema chain
  pkg/query/logical/measure/measure_plan_aggregation.go
  pkg/query/logical/measure/measure_plan_groupby.go
  test/cases/measure/data/input/top.yaml
  test/cases/measure/measure.go
  test/e2e-v2/cases/storage/expected/metrics-top-service.yml
  test/e2e-v2/cases/storage/storage-cases.yaml
Labels: bug

#254 Bump golang.org/x/net from 0.2.0 to 0.7.0
  dist/LICENSE
  go.mod
  go.sum
Labels: vulnerability

#255 Add a timeout to all go leaking checkers
  banyand/liaison/grpc/registry_test.go
  banyand/measure/metadata_test.go
  banyand/metadata/schema/checker_test.go
  banyand/stream/metadata_test.go
  test/integration/cold_query/query_suite_test.go
  test/integration/load/load_suite_test.go
  test/integration/other/measure_test.go
  test/integration/other/property_test.go
  test/integration/other/tls_test.go
  test/integration/query/query_suite_test.go
Labels: bug

#256 Update change log
  CHANGES.md
Labels: documentation, chore

#253 Write-ahead Logging interface
  api/common/id.go
  pkg/wal/wal.go
Labels: enhancement
