Repository apache/skywalking-banyandb, pull requests merged in 2023-06, with the labels that each got.

#277 Add system information endpoint
  .github/workflows/ci.yml
  .github/workflows/e2e.storage.yml
  .github/workflows/publish-docker.yml
  .github/workflows/test.yml
  CHANGES.md
  CONTRIBUTING.md
  banyand/liaison/grpc/server.go
  banyand/liaison/http/server.go
  banyand/measure/service.go
  banyand/metadata/schema/etcd.go
  banyand/observability/meter_noop.go
  banyand/observability/meter_prom.go
  banyand/observability/service.go
  banyand/observability/system.go
  banyand/stream/service.go
  dist/LICENSE
  docs/installation.md
  ui/LICENSE
  ui/package-lock.json
  ui/package.json
  ui/vite.config.js
Labels: ui

#282 Generalize the index's docID to uint64.
  CHANGES.md
  banyand/tsdb/block.go
  banyand/tsdb/series_seek_filter.go
  banyand/tsdb/series_seek_sort.go
  pkg/index/index.go
  pkg/index/inverted/inverted.go
  pkg/index/inverted/inverted_test.go
  pkg/index/lsm/lsm.go
  pkg/index/lsm/search.go
  pkg/index/posting/posting.go
  pkg/index/posting/roaring/roaring.go
  pkg/index/testcases/duration.go
  pkg/index/testcases/service_name.go
  pkg/query/logical/index_filter.go
Labels: enhancement

#290 Update docs for 0.4.0 release
  CHANGES.md
  README.md
  docs/clients.md
  docs/concept/data-model.md
Labels: documentation, chore

#289 Push the max int as limitation
  CHANGES.md
  pkg/query/logical/measure/measure_analyzer.go
Labels: bug

#291 polish data model doc
  docs/concept/data-model.md
Labels: documentation, chore
