Repository apache/skywalking-banyandb, pull requests merged in 2023-05, with the labels that each got.

#269 fix some errors in docs
  docs/concept/data-model.md
  docs/crud/group.md
  docs/crud/index_rule.md
  docs/crud/measure/schema.md
  docs/crud/stream/schema.md
Labels: documentation

#270 Refine load testing issues and optimize performance
  CHANGES.md
  banyand/Dockerfile
  banyand/k8s.yml
  banyand/kv/kv.go
  banyand/measure/measure_write.go
  banyand/query/processor.go
  banyand/tsdb/block.go
  banyand/tsdb/buffer.go
  banyand/tsdb/shard.go
  pkg/encoding/encoder.go
  pkg/encoding/encoding.go
  pkg/index/lsm/iterator.go
  pkg/index/lsm/lsm.go
  pkg/index/lsm/lsm_test.go
  pkg/index/lsm/search.go
  pkg/query/logical/common.go
  pkg/query/logical/iter.go
  pkg/query/logical/measure/measure_plan_aggregation.go
  pkg/query/logical/measure/measure_plan_groupby.go
  pkg/query/logical/measure/measure_plan_indexscan_local.go
  pkg/query/logical/measure/measure_plan_top.go
  pkg/query/logical/stream/stream_plan_indexscan_local.go
Labels: bug, enhancement

#271 Fix docs crud examples error
  CHANGES.md
  docs/crud/index_rule_binding.md
  docs/crud/measure/schema.md
  docs/crud/property.md
  docs/crud/stream/query.md
  docs/crud/stream/schema.md
Labels: bug, documentation

#272 Fix resource corrupts caused by update indexRule operation
  CHANGES.md
  banyand/metadata/schema/etcd_test.go
  banyand/metadata/schema/index.go
Labels: bug

#273 modified TestGoVersion to check Go CPU architectue
  CHANGES.md
  scripts/ci/check/version_test.go
Labels: chore
