Repository apache/skywalking-banyandb, pull requests merged in 2023-07, with the labels that each got.

#295 polish cmd flags and keep the style of linking multiple words with "-".
  banyand/internal/cmd/standalone.go
  banyand/liaison/grpc/server.go
  banyand/liaison/http/server.go
  banyand/metadata/metadata.go
  docs/installation.md
Labels: chore

#296 List all properties in a group
  CHANGES.md
  api/proto/banyandb/common/v1/common.proto
  api/proto/banyandb/property/v1/rpc.proto
  bydbctl/internal/cmd/property.go
  bydbctl/internal/cmd/property_test.go
  bydbctl/internal/cmd/root.go
  docs/crud/property.md
  test/integration/other/property_test.go
Labels: enhancement

#297 Bump several dependencies and tools
  CHANGES.md
  Makefile
  api/proto/banyandb/database/v1/rpc.proto
  api/proto/banyandb/measure/v1/rpc.proto
  api/proto/banyandb/property/v1/rpc.proto
  api/proto/banyandb/stream/v1/rpc.proto
  banyand/measure/measure_suite_test.go
  banyand/metadata/schema/etcd.go
  banyand/stream/stream_suite_test.go
  banyand/tsdb/bucket/queue.go
  dist/LICENSE
  dist/licenses/license-github.com-fsnotify-fsnotify.txt
  dist/licenses/license-github.com-go-task-slim-sprig.txt
  dist/licenses/license-github.com-google-pprof.txt
  dist/licenses/license-github.com-hashicorp-golang-lru-v2.txt
  dist/licenses/license-github.com-mattn-go-colorable.txt
  dist/licenses/license-github.com-mattn-go-isatty.txt
  dist/licenses/license-go.opentelemetry.io-otel-metric.txt
  dist/licenses/license-go.uber.org-mock.txt
  dist/licenses/license-golang.org-x-tools.txt
  dist/licenses/license-google.golang.org-genproto-googleapis-api.txt
  dist/licenses/license-google.golang.org-genproto-googleapis-rpc.txt
  go.mod
  go.sum
  pkg/flow/streaming/sources/channel_test.go
  pkg/test/flags/flags.go
  pkg/test/flow/slice_test.go
  pkg/test/matcher.go
  scripts/build/generate_go.mk
  scripts/build/version.mk
  test/integration/load/load_suite_test.go
  test/integration/query/query_suite_test.go
  test/stress/cases/istio/istio_suite_test.go
Labels: chore

#298 fix: BanyanDB ui unable to load icon
  CHANGES.md
  ui/src/components/Header/components/header.vue
Labels: bug, ui

#302 Document the clustering
  CHANGES.md
  README.md
  docs/concept/clustering.md
Labels: documentation

#308 Update menu.yml
  docs/menu.yml
Labels: documentation
