Repository apache/skywalking-banyandb, pull requests merged in 2024-07, with the labels that each got.

#482 Assign a separate lookup table to each group
  CHANGES.md
  pkg/cmdsetup/liaison.go
  pkg/node/interface.go
  pkg/node/maglev.go
  pkg/node/maglev_test.go
Labels: enhancement

#481 [GsoC][BanyanDB] Self-Observability: Add Metrics - Uptime, Disk
  banyand/observability/metrics_system.go
Labels: enhancement

#478 [OSPP] Submitted the delta and cumulative API design plan,
  api/proto/banyandb/measure/v1/write.proto
  docs/api-reference.md
Labels: enhancement, api

#483 Convert the async local pipeline to a sync pipeline
  CHANGES.md
  pkg/bus/bus.go
Labels: enhancement

#484 [UI] Vendor update July 2024
  dist/LICENSE
  dist/licenses/ui-licenses/license-braces.txt
  dist/licenses/ui-licenses/license-lru-cache.txt
  dist/licenses/ui-licenses/license-sass.txt
  dist/licenses/ui-licenses/license-yallist.txt
  ui/LICENSE
  ui/package-lock.json
Labels: dependencies

#485 Support duplicated data for Stream
  CHANGES.md
  banyand/dquery/stream.go
  banyand/internal/storage/index.go
  banyand/internal/storage/version.go
  banyand/internal/storage/versions.yml
  banyand/measure/block.go
  banyand/measure/query.go
  banyand/query/processor.go
  banyand/stream/benchmark_test.go
  banyand/stream/block.go
  banyand/stream/block_test.go
  banyand/stream/block_writer.go
  banyand/stream/elements.go
  banyand/stream/index.go
  banyand/stream/merger_test.go
  banyand/stream/part_test.go
  banyand/stream/query.go
  banyand/stream/query_test.go
  banyand/stream/tstable_test.go
  banyand/stream/write.go
  bydbctl/internal/cmd/stream_test.go
  pkg/index/index.go
  pkg/index/inverted/inverted.go
  pkg/index/inverted/inverted_series_test.go
  pkg/index/inverted/inverted_test.go
  pkg/index/inverted/sort.go
  pkg/index/inverted/sort_test.go
  pkg/index/testcases/duration.go
  pkg/index/testcases/service_name.go
  pkg/pb/v1/metadata.go
  pkg/query/executor/interface.go
  pkg/query/logical/measure/measure_plan_indexscan_local.go
  pkg/query/logical/stream/stream_analyzer.go
  pkg/query/logical/stream/stream_plan_distributed.go
  pkg/query/logical/stream/stream_plan_indexscan_local.go
  pkg/query/logical/stream/stream_plan_tag_filter.go
  pkg/test/helpers/context.go
  pkg/test/stream/etcd.go
  pkg/test/stream/testdata/index_rule_bindings/duplicated.json
  pkg/test/stream/testdata/index_rule_bindings/sw.json
  pkg/test/stream/testdata/streams/duplicated.json
  pkg/test/stream/testdata/streams/sw.json
  pkg/timestamp/range_test.go
  test/cases/init.go
  test/cases/stream/data/data.go
  test/cases/stream/data/input/duplicated_all.yaml
  test/cases/stream/data/input/duplicated_entity_filter.yaml
  test/cases/stream/data/input/duplicated_index_filter.yaml
  test/cases/stream/data/input/duplicated_order_by_filter.yaml
  test/cases/stream/data/input/duplicated_order_by_index.yaml
  test/cases/stream/data/input/sort_duration_no_index_limit.yaml
  test/cases/stream/data/testdata/duplicated.json
  test/cases/stream/data/testdata/sw.json
  test/cases/stream/data/want/duplicated_all.yaml
  test/cases/stream/data/want/duplicated_entity_filter.yaml
  test/cases/stream/data/want/duplicated_index_filter.yaml
  test/cases/stream/data/want/duplicated_order_by_filter.yaml
  test/cases/stream/data/want/duplicated_order_by_index.yaml
  test/cases/stream/data/want/sort_duration_no_index_limit.yaml
  test/cases/stream/stream.go
Labels: bug

#487 Clean up todo
  api/proto/banyandb/measure/v1/topn.proto
  banyand/Makefile
  banyand/dquery/measure.go
  banyand/dquery/stream.go
  banyand/dquery/topn.go
  banyand/internal/bucket/bucket.go
  banyand/internal/bucket/bucket_suite_test.go
  banyand/internal/bucket/queue.go
  banyand/internal/bucket/queue_test.go
  banyand/internal/bucket/strategy.go
  banyand/internal/bucket/strategy_test.go
  banyand/internal/storage/index.go
  banyand/internal/storage/segment.go
  banyand/internal/storage/shard.go
  banyand/liaison/grpc/measure.go
  banyand/liaison/grpc/stream.go
  banyand/measure/column.go
  banyand/measure/part_iter_test.go
  banyand/measure/topn.go
  banyand/metadata/embeddedetcd/server.go
  banyand/query/processor.go
  banyand/query/processor_topn.go
  banyand/stream/part_iter_test.go
  banyand/stream/tag.go
  bydbctl/internal/cmd/rest.go
  dist/LICENSE
  dist/licenses/license-github.com-hashicorp-golang-lru-v2.txt
  docs/api-reference.md
  docs/observability.md
  go.mod
  go.sum
  pkg/cmdsetup/data.go
  pkg/convert/number_test.go
  pkg/flow/streaming/streaming.go
  pkg/flow/streaming/unary.go
  pkg/fs/local_file_system.go
  pkg/query/logical/measure/schema.go
  pkg/schema/cache.go
  test/docker/base-compose.yml
  test/integration/load/load_suite_test.go
  test/stress/trace/docker-compose-cluster.yaml
  test/stress/trace/docker-compose-single.yaml
Labels: chore

#488 Update data generator repo
  test/e2e-v2/script/env
  test/stress/classic/env
  test/stress/classic/env.dev
  test/stress/trace/docker-compose-cluster.yaml
  test/stress/trace/docker-compose-single.yaml
  test/stress/trace/env
Labels: docker

#489 Increase Segment Ref Count Wrongly
  CHANGES.md
  banyand/internal/storage/segment.go
  banyand/measure/tstable.go
  banyand/stream/tstable.go
Labels: bug

#490 [GSOC] [Self-Observability] Suppress Error When Getting Path Stat
  banyand/observability/metrics_system.go
Labels: bug

#493 Update the tsdb.md to represent the latest structure
  docs/concept/tsdb.md
Labels: documentation

#494 Introduce new doc menu structure, add installation on Docker and Kubernetes
  CHANGES.md
  docs/guides/quick-start/docker-compose.yaml
  docs/guides/quick-start/quick-start.md
  docs/installation/docker.md
  docs/installation/kubernetes.md
  docs/menu.yml
Labels: documentation

#496 [GSoC] [UI] Dashboard Page
  docs/installation/cluster.md
  docs/observability.md
  test/docker/base-compose.yml
  ui/src/components/Header/components/header.vue
  ui/src/components/Header/index.vue
  ui/src/components/Read/index.vue
  ui/src/styles/elementPlus.scss
  ui/src/views/Dashboard/index.vue
Labels: enhancement, ui

#497 [GSoc] [Self-Observability] Fix dashboard disk N/A in standalone mode
  ui/src/views/Dashboard/index.vue
Labels: bug

#498 update docs.
  CHANGES.md
  docs/concept/data-model.md
  docs/crud/group.md
  docs/crud/index_rule.md
  docs/crud/index_rule_binding.md
  docs/crud/measure/query.md
  docs/crud/measure/schema.md
  docs/crud/property.md
  docs/crud/stream/query.md
  docs/crud/stream/schema.md
  docs/guides/quick-start/docker-compose.yaml
  docs/guides/quick-start/quick-start.md
  docs/installation/kubernetes.md
  docs/menu.yml
Labels: documentation

#499 Fix series match crash
  banyand/internal/storage/index.go
  banyand/measure/query.go
  banyand/stream/query.go
  bydbctl/internal/cmd/measure_test.go
  bydbctl/internal/cmd/stream_test.go
  pkg/pb/v1/series.go
Labels: bug

#500 Improve round robin selector
  banyand/internal/storage/segment.go
  docs/concept/clustering.md
  pkg/cmdsetup/liaison.go
  pkg/node/interface.go
  pkg/node/maglev.go
  pkg/node/round_robin.go
  pkg/node/round_robin_test.go
  test/docker/base-compose.yml
  test/e2e-v2/script/env
  test/stress/classic/env
  test/stress/classic/env.dev
  test/stress/trace/env
Labels: bug

#501 Fix Distributed Query Bug
  CHANGES.md
  pkg/query/logical/measure/measure_plan_distributed.go
  pkg/query/logical/stream/stream_plan_distributed.go
  test/cases/measure/data/input/limit.yaml
  test/cases/measure/data/want/limit.yaml
  test/cases/stream/data/input/offset.yaml
  test/cases/stream/data/want/offset.yaml
Labels: bug

#502 Measure index
  CHANGES.md
  banyand/internal/storage/index.go
  banyand/internal/storage/index_test.go
  banyand/internal/storage/storage.go
  banyand/measure/block.go
  banyand/measure/measure.go
  banyand/measure/query.go
  banyand/measure/write.go
  banyand/stream/index.go
  banyand/stream/query.go
  banyand/stream/stream.go
  pkg/index/index.go
  pkg/index/inverted/inverted.go
  pkg/index/inverted/inverted_series.go
  pkg/index/inverted/inverted_series_test.go
  pkg/index/inverted/inverted_test.go
  pkg/index/inverted/sort.go
  pkg/index/inverted/sort_test.go
  pkg/partition/index.go
  pkg/pb/v1/value.go
  test/cases/measure/data/input/entity.yaml
  test/cases/measure/data/input/entity_in.yaml
  test/cases/measure/data/input/entity_service.yaml
  test/cases/measure/data/input/no_field.yaml
  test/cases/measure/data/want/entity.yaml
  test/cases/measure/data/want/entity_in.yaml
  test/cases/measure/data/want/entity_service.yaml
  test/cases/measure/data/want/no_field.yaml
  test/stress/istio/report.md
  test/stress/istio/testdata/metrics/data.csv
  test/stress/istio/testdata/metrics/intermediate.csv
  test/stress/istio/testdata/metrics/result.csv
Labels: enhancement
