Repository apache/skywalking-banyandb, pull requests merged in 2024-10, with the labels that each got.

#547 Fix the bug that the long running query doesn't stop when the context is canceled
  CHANGES.md
  banyand/dquery/measure.go
  banyand/dquery/stream.go
  banyand/dquery/topn.go
  banyand/internal/storage/index.go
  banyand/liaison/grpc/measure.go
  banyand/liaison/grpc/stream.go
  banyand/measure/query.go
  banyand/measure/query_test.go
  banyand/measure/topn.go
  banyand/measure/write.go
  banyand/metadata/schema/etcd.go
  banyand/query/processor.go
  banyand/query/processor_topn.go
  banyand/queue/local.go
  banyand/queue/pub/pub.go
  banyand/queue/pub/pub_test.go
  banyand/queue/sub/sub.go
  banyand/stream/index.go
  banyand/stream/query.go
  banyand/stream/write.go
  docs/menu.yml
  pkg/bus/bus.go
  pkg/bus/bus_test.go
  pkg/grpchelper/client.go
  pkg/index/index.go
  pkg/index/inverted/inverted.go
  pkg/index/inverted/inverted_series.go
  pkg/index/inverted/sort.go
  pkg/index/inverted/sort_test.go
  pkg/index/testcases/duration.go
  pkg/logger/setting.go
  pkg/meter/native/collection.go
  pkg/query/logical/measure/measure_plan_indexscan_local.go
  pkg/query/model/model.go
Labels: bug

#548 Fix bugs and add docs
  CHANGES.md
  banyand/Dockerfile
  banyand/measure/block.go
  banyand/measure/block_test.go
  banyand/measure/query.go
  banyand/measure/write.go
  banyand/metadata/schema/etcd.go
  banyand/queue/sub/sub.go
  banyand/stream/block.go
  banyand/stream/block_test.go
  banyand/stream/query.go
  banyand/stream/write.go
  docs/concept/tsdb.md
  docs/menu.yml
  pkg/index/inverted/inverted.go
  pkg/index/inverted/inverted_series.go
  pkg/query/logical/stream/stream_plan_indexscan_local.go
  test/docker/Dockerfile
Labels: bug, documentation

#549 Fix measure merging issue
  CHANGES.md
  banyand/measure/block.go
  banyand/measure/merger.go
  banyand/measure/merger_test.go
  banyand/measure/tstable_test.go
Labels: bug

#550 Fix metrics system typo
  CHANGES.md
  banyand/observability/metrics_system.go
Labels: bug

#551 Improve the description of the memory in observability doc
  CHANGES.md
  docs/operation/grafana-cluster.json
  docs/operation/observability.md
Labels: documentation

#552 Fix the bug that TopN processing item leak
  CHANGES.md
  banyand/measure/topn.go
  banyand/measure/write.go
  pkg/flow/streaming/streaming_test.go
  pkg/flow/streaming/topn.go
  pkg/flow/streaming/topn_test.go
Labels: bug

#553 Add the `bydbctl analyze series` command to analyze the series data.
  CHANGES.md
  bydbctl/internal/cmd/analyze.go
  bydbctl/internal/cmd/analyze_test.go
  bydbctl/internal/cmd/root.go
  docs/interacting/bydbctl/analyze.md
  docs/menu.yml
  go.mod
  pkg/index/index.go
  pkg/index/inverted/inverted_series.go
  pkg/pb/v1/value.go
Labels: enhancement
