Repository apache/skywalking-banyandb, pull requests merged in 2024-05, with the labels that each got.

#442 Long running testing
  banyand/internal/storage/index.go
  banyand/internal/storage/index_test.go
  banyand/internal/storage/retention.go
  banyand/internal/storage/rotation.go
  banyand/internal/storage/rotation_test.go
  banyand/internal/storage/segment.go
  banyand/internal/storage/shard.go
  banyand/internal/storage/storage.go
  banyand/internal/storage/tsdb.go
  banyand/measure/datapoints.go
  banyand/measure/query.go
  banyand/measure/write.go
  banyand/stream/elements.go
  banyand/stream/query.go
  banyand/stream/write.go
  docs/installation/binaries.md
  pkg/index/index.go
  pkg/index/inverted/inverted_series.go
  pkg/index/inverted/inverted_series_test.go
  pkg/pb/v1/metadata.go
  pkg/query/logical/measure/measure_plan_distributed.go
  pkg/query/logical/measure/measure_plan_indexscan_local.go
  pkg/query/logical/measure/topn_plan_localscan.go
  pkg/query/logical/stream/stream_plan_indexscan_local.go
  pkg/test/flags/flags.go
  pkg/test/helpers/file.go
  pkg/test/space.go
  pkg/test/stream/testdata/group.json
  pkg/timestamp/range.go
  test/integration/load/load_suite_test.go
  test/stress/istio/Makefile
  test/stress/istio/istio_suite_test.go
  test/stress/istio/repo.go
  test/stress/istio/report.md
  test/stress/istio/testdata/metrics/data.csv
  test/stress/istio/testdata/metrics/intermediate.csv
  test/stress/istio/testdata/metrics/result.csv
  test/stress/trace/docker-compose-single.yaml
  test/stress/trace/env
  test/stress/trace/log4j2.xml
  test/stress/trace/segment.tpl.json
Labels: documentation, enhancement

#443 Change default null value
  banyand/measure/query.go
  banyand/stream/query.go
  pkg/pb/v1/metadata.go
  test/cases/topn/data/want/null_group.yaml
  test/e2e-v2/script/env
  test/stress/classic/env
  test/stress/classic/env.dev
Labels: bug

#444 Switch e2e image repo to ghcr
  test/docker/base-compose.yml
  test/e2e-v2/script/env
  test/stress/classic/env
  test/stress/classic/env.dev
  test/stress/trace/docker-compose-cluster.yaml
  test/stress/trace/docker-compose-single.yaml
  test/stress/trace/env
Labels: docker, testing

#445 Fix topn query nil and add more context to err
  CHANGES.md
  banyand/internal/storage/index.go
  banyand/query/processor_topn.go
  pkg/index/index.go
  test/stress/vm/Makefile
  test/stress/vm/docker-compose.yaml
Labels: bug

#448 Data race in the hot series index selection
  CHANGES.md
  banyand/internal/storage/index.go
Labels: bug

#449 Add benchmarks for stream filtering and sorting
  CHANGES.md
  banyand/stream/benchmark_test.go
  banyand/stream/index.go
  banyand/stream/iter.go
  banyand/stream/query.go
  pkg/timestamp/range.go
Labels: testing

#451 Remove SetSchema from measure cache
  CHANGES.md
  banyand/measure/query.go
  banyand/measure/write.go
  banyand/metadata/schema/watcher.go
  banyand/query/processor_topn.go
  pkg/schema/cache.go
  pkg/schema/init.go
Labels: bug

#440 Improve filtering performance of Stream
  banyand/cmd/server/main.go
  banyand/measure/query.go
  banyand/stream/benchmark_test.go
  banyand/stream/block.go
  banyand/stream/index.go
  banyand/stream/iter_builder.go
  banyand/stream/query.go
  banyand/stream/stream.go
  pkg/pb/v1/metadata.go
  pkg/query/executor/interface.go
  pkg/query/logical/stream/stream_plan_indexscan_local.go
  pkg/timestamp/range.go
  test/cases/stream/data/input/order_asc.yaml
  test/cases/stream/data/input/order_desc.yaml
  test/cases/stream/data/want/order_asc.yaml
  test/cases/stream/data/want/order_desc.yaml
  test/cases/stream/stream.go
Labels: enhancement

#452 Fix duplicated items in the query aggregation top-n list
  CHANGES.md
  banyand/measure/query.go
  pkg/pb/v1/metadata.go
  pkg/query/logical/measure/measure_analyzer.go
  pkg/query/logical/measure/measure_plan_distributed.go
  pkg/query/logical/measure/measure_plan_indexscan_local.go
  pkg/schema/cache.go
  pkg/test/measure/testdata/index_rule_bindings/service_instance_latency_minute.json
  pkg/test/measure/testdata/measures/service_instance_latency_minute.json
  test/cases/init.go
  test/cases/measure/data/input/bottom_entity.yaml
  test/cases/measure/data/input/bottom_entity_svc.yaml
  test/cases/measure/data/input/top_entity.yaml
  test/cases/measure/data/input/top_entity_svc.yaml
  test/cases/measure/data/testdata/service_instance_latency_minute_data.json
  test/cases/measure/data/testdata/service_instance_latency_minute_data1.json
  test/cases/measure/data/want/bottom_entity.yaml
  test/cases/measure/data/want/bottom_entity_svc.yaml
  test/cases/measure/data/want/top_entity.yaml
  test/cases/measure/data/want/top_entity_svc.yaml
  test/cases/measure/measure.go
  test/stress/classic/docker-compose.yaml
Labels: bug

#455 Fix several issues of topN pre-calculation
  CHANGES.md
  banyand/internal/storage/index.go
  banyand/measure/block_metadata_test.go
  banyand/measure/block_writer.go
  banyand/measure/column.go
  banyand/measure/topn.go
  banyand/query/processor_topn.go
  banyand/queue/sub/sub.go
  banyand/stream/block_metadata.go
  banyand/stream/block_metadata_test.go
  banyand/stream/block_writer.go
  banyand/stream/tag.go
  pkg/flow/streaming/sliding_window.go
  pkg/flow/streaming/sliding_window_test.go
  pkg/flow/streaming/streaming.go
  pkg/flow/streaming/streaming_test.go
  pkg/flow/streaming/topn.go
  pkg/flow/streaming/topn_test.go
  pkg/flow/types.go
  pkg/pb/v1/series.go
  pkg/pb/v1/series_test.go
  pkg/pb/v1/value.go
  pkg/query/logical/measure/topn_analyzer.go
  pkg/schema/init.go
  pkg/test/measure/testdata/topn_aggregations/service_instance_endpoint_cpm_minute_top_bottom_100.json
  pkg/test/setup/setup.go
  test/cases/measure/data/testdata/service_instance_endpoint_cpm_minute_data.json
  test/cases/measure/data/testdata/service_instance_endpoint_cpm_minute_data1.json
  test/cases/measure/data/testdata/service_instance_endpoint_cpm_minute_data2.json
  test/cases/topn/data/want/null_group.yaml
Labels: bug

#456 Remove self-ob group
  banyand/observability/self_observability.go
  banyand/observability/service.go
Labels: chore

#453 [GsoC][BanyanDB] Self-Observability: Run Time Modes
  .github/workflows/publish-docker.yml
  banyand/observability/collector.go
  banyand/observability/meter_noop.go
  banyand/observability/meter_prom.go
  banyand/observability/metrics_system.go
  banyand/observability/service.go
  banyand/observability/system.go
  banyand/observability/type.go
  docker/Dockerfile
  docs/observability.md
Labels: enhancement, go

#454 docs: optimized the README and the Standalone page.
  CONTRIBUTING.md
  docs/README.md
  docs/crud/index_rule_binding.md
  docs/installation/binaries.md
  docs/installation/cluster.md
  docs/installation/standalone.md
  docs/menu.yml
Labels: documentation

#458 Build Docker multi-arch without attestation manifest
  scripts/build/docker.mk
Labels: docker
