Repository apache/skywalking-banyandb, pull requests merged in 2024-06, with the labels that each got.

#461 Add Trace API
  api/proto/banyandb/common/v1/trace.proto
  api/proto/banyandb/measure/v1/query.proto
  api/proto/banyandb/stream/v1/query.proto
  docs/api-reference.md
Labels: api

#460 [GsoC][BanyanDB] Self Observability: Fix Metrics Creation
  banyand/observability/collector.go
  banyand/observability/instrument.go
  banyand/observability/metrics_system.go
  banyand/observability/service.go
Labels: bug

#463 [UI] Fix yaml code mirror to http read request
  ui/src/components/Read/index.vue
Labels: bug

#464 Fix the filtering of stream in descending order by timestamp
  CHANGES.md
  banyand/stream/index.go
  banyand/stream/query.go
  pkg/timestamp/range.go
  pkg/timestamp/range_test.go
  test/cases/stream/data/input/filter_order_desc.yaml
  test/cases/stream/data/want/filter_order_desc.yaml
  test/cases/stream/stream.go
Labels: bug

#466 Check Unregistered Nodes in Background
  CHANGES.md
  banyand/queue/pub/client.go
  banyand/queue/pub/client_test.go
  banyand/queue/pub/pub.go
  test/stress/istio/istio_suite_test.go
Labels: enhancement

#468 Add version to timestamp file
  CHANGES.md
  api/proto/banyandb/measure/v1/query.proto
  api/proto/banyandb/measure/v1/write.proto
  banyand/liaison/grpc/measure.go
  banyand/measure/block.go
  banyand/measure/block_metadata.go
  banyand/measure/block_metadata_test.go
  banyand/measure/block_test.go
  banyand/measure/block_writer.go
  banyand/measure/datapoints.go
  banyand/measure/measure.go
  banyand/measure/merger.go
  banyand/measure/merger_test.go
  banyand/measure/part.go
  banyand/measure/part_iter.go
  banyand/measure/part_test.go
  banyand/measure/query.go
  banyand/measure/query_test.go
  banyand/measure/tstable_test.go
  banyand/measure/write.go
  banyand/stream/block.go
  docs/api-reference.md
  pkg/encoding/encoding.go
  pkg/encoding/int_list.go
  pkg/pb/v1/metadata.go
  pkg/query/logical/measure/measure_plan_indexscan_local.go
  test/cases/measure/data/data.go
  test/cases/measure/data/testdata/service_instance_endpoint_cpm_minute_data1.json
Labels: bug

#465 Return the tagValue of sorted tag
  api/proto/banyandb/database/v1/schema.proto
  banyand/internal/storage/index.go
  banyand/stream/index.go
  banyand/stream/iter.go
  banyand/stream/write.go
  docs/api-reference.md
  pkg/index/index.go
  pkg/index/inverted/inverted.go
  pkg/index/inverted/sort.go
  pkg/index/inverted/sort_test.go
  pkg/index/testcases/duration.go
  pkg/query/logical/common.go
  pkg/query/logical/plan.go
Labels: enhancement

#459 Improve sorting performance of Stream
  CHANGES.md
  banyand/internal/storage/index.go
  banyand/stream/benchmark_test.go
  banyand/stream/block.go
  banyand/stream/index.go
  banyand/stream/iter.go
  banyand/stream/iter_builder.go
  banyand/stream/part.go
  banyand/stream/query.go
  banyand/stream/query_test.go
  banyand/stream/stream.go
  banyand/stream/tstable.go
  pkg/index/index.go
  pkg/index/inverted/inverted.go
  pkg/index/inverted/sort.go
  pkg/index/inverted/sort_test.go
  pkg/index/testcases/duration.go
  pkg/pb/v1/metadata.go
  pkg/query/executor/interface.go
  pkg/query/logical/stream/stream_plan_indexscan_local.go
Labels: enhancement

#467 [GsoC][BanyanDB] Self-Observability: Write Metric Data to Measure In Standalone Mode
  banyand/observability/instrument.go
  banyand/observability/meter_native.go
  banyand/observability/meter_prom.go
  banyand/observability/metrics_system.go
  banyand/observability/service.go
  pkg/cmdsetup/data.go
  pkg/cmdsetup/liaison.go
  pkg/cmdsetup/standalone.go
  pkg/meter/native/collection.go
  pkg/meter/native/instruments.go
  pkg/meter/native/provider.go
  pkg/meter/native/vec.go
Labels: enhancement

#469 Deduplicate data points in distributed query
  CHANGES.md
  api/proto/banyandb/measure/v1/query.proto
  docs/api-reference.md
  pkg/query/logical/measure/measure_plan_distributed.go
  pkg/query/logical/measure/measure_plan_distributed_test.go
  pkg/query/logical/measure/measure_plan_indexscan_local.go
  test/cases/measure/data/data.go
Labels: bug

#471 Fix the data node can't re-register to etcd
  CHANGES.md
  banyand/internal/storage/segment.go
  banyand/internal/storage/version.go
  banyand/metadata/schema/etcd.go
  banyand/metadata/schema/etcd_test.go
  banyand/metadata/schema/register_test.go
  banyand/metadata/schema/watcher_test.go
  pkg/logger/logger.go
Labels: bug

#473 Fix several bugs
  CHANGES.md
  banyand/metadata/client.go
  banyand/metadata/embeddedserver/server.go
  banyand/observability/service.go
  banyand/queue/pub/client.go
  banyand/stream/query.go
  bydbctl/internal/cmd/property.go
  bydbctl/internal/cmd/property_test.go
  bydbctl/internal/cmd/root.go
  pkg/cmdsetup/root.go
  pkg/index/inverted/inverted.go
  pkg/index/inverted/sort.go
Labels: bug

#474 Stop check loop once the node is healthy
  banyand/queue/pub/client.go
Labels: bug

#476 Add the measure query trace system
  CHANGES.md
  api/proto/banyandb/common/v1/trace.proto
  banyand/dquery/dquery.go
  banyand/dquery/measure.go
  banyand/internal/storage/index.go
  banyand/liaison/grpc/measure.go
  banyand/measure/introducer.go
  banyand/measure/query.go
  banyand/measure/trace.go
  banyand/metadata/client.go
  banyand/metadata/embeddedserver/server.go
  banyand/metadata/metadata_test.go
  banyand/query/processor.go
  banyand/stream/introducer.go
  docs/api-reference.md
  pkg/query/doc.go
  pkg/query/logical/index_filter.go
  pkg/query/logical/measure/measure_plan_distributed.go
  pkg/query/logical/measure/measure_plan_indexscan_local.go
  pkg/query/tracer.go
  pkg/query/tracer_test.go
  pkg/test/stream/etcd.go
  test/stress/trace/docker-compose-cluster.yaml
Labels: enhancement

#480 Set duration unit to nanosecond
  banyand/internal/storage/segment.go
  pkg/query/tracer.go
Labels: bug
