Repository apache/skywalking-banyandb, pull requests merged in 2024-01, with the labels that each got.

#365 chore: rename conjecture to Conjectrue
  README.md
Labels: chore

#367 Introduce sequential read for merging
  banyand/internal/storage/tsdb.go
  banyand/measure/block.go
  banyand/measure/block_reader.go
  banyand/measure/block_reader_test.go
  banyand/measure/block_test.go
  banyand/measure/column.go
  banyand/measure/flusher.go
  banyand/measure/gc.go
  banyand/measure/introducer.go
  banyand/measure/merger.go
  banyand/measure/merger_test.go
  banyand/measure/part.go
  banyand/measure/part_iter.go
  banyand/measure/part_iter_test.go
  banyand/measure/primary_metadata.go
  banyand/measure/tstable.go
  banyand/measure/tstable_test.go
  pkg/bytes/buffer.go
  pkg/fs/file_system.go
  pkg/fs/local_file_system.go
  pkg/fs/local_file_system_test.go
  pkg/index/inverted/inverted.go
  pkg/index/inverted/inverted_test.go
  scripts/build/version.mk
Labels: enhancement

#372 Add sequential writer for merging
  banyand/internal/storage/index.go
  banyand/internal/storage/index_test.go
  banyand/internal/storage/tsdb.go
  banyand/measure/block.go
  banyand/measure/block_reader.go
  banyand/measure/block_test.go
  banyand/measure/block_writer.go
  banyand/measure/column_test.go
  banyand/measure/merger.go
  banyand/measure/metadata.go
  banyand/measure/primary_metadata.go
  pkg/bytes/buffer.go
  pkg/fs/file_system.go
  pkg/fs/local_file_system.go
  pkg/fs/local_file_system_test.go
  pkg/index/index.go
  pkg/index/inverted/inverted.go
  pkg/index/inverted/inverted_series_test.go
  pkg/index/lsm/lsm.go
  test/integration/standalone/query_ondisk/query_ondisk_suite_test.go
  test/stress/cases/istio/report.md
  test/stress/cases/istio/testdata/metrics/data.csv
  test/stress/cases/istio/testdata/metrics/intermediate.csv
  test/stress/cases/istio/testdata/metrics/result.csv
Labels: testing

#371 Introduce compaction algorithm
  banyand/measure/measure.go
  banyand/measure/merger.go
  banyand/measure/merger_policy.go
  banyand/measure/metadata.go
  banyand/measure/query_test.go
  banyand/measure/service.go
  banyand/measure/tstable.go
  banyand/measure/tstable_test.go
Labels: enhancement

#378 Fix stream startup warning
  banyand/stream/index.go
  banyand/stream/part.go
  banyand/stream/tstable.go
Labels: bug

#382 Polish indexScan plan for stream
  pkg/query/logical/stream/stream_plan_indexscan_local.go
Labels: bug

#383 Remove meta in part
  banyand/measure/part.go
  banyand/stream/part.go
Labels: bug
