Repository apache/skywalking-banyandb, pull requests merged in 2024-04, with the labels that each got.

#424 chore: improve binaries.md and standalone.md
  docs/installation/binaries.md
  docs/installation/standalone.md
Labels: chore

#425 Add preload for the TopN query of index
  CHANGES.md
  banyand/internal/storage/index.go
  banyand/internal/storage/storage.go
  banyand/measure/query.go
  banyand/stream/index.go
  banyand/stream/iter_builder.go
  banyand/tsdb/series_seek_sort.go
  banyand/tsdb/seriesdb.go
  pkg/index/index.go
  pkg/index/inverted/inverted.go
  pkg/index/inverted/sort.go
  pkg/index/lsm/search.go
  pkg/index/testcases/duration.go
  pkg/iter/sort/sort.go
  test/stress/trace/Makefile
  test/stress/trace/trace_suite_test.go
Labels: enhancement, testing

#426 Add more test cases and fix some issues found in the test
  banyand/measure/block.go
  banyand/measure/block_metadata.go
  banyand/stream/block.go
  banyand/stream/block_metadata.go
  pkg/test/query/trace.go
  test/stress/trace/trace_suite_test.go
Labels: bug, testing

#428 Implement GC for SeriesDatabase of TSDB
  banyand/internal/storage/index.go
  banyand/internal/storage/index_test.go
  banyand/internal/storage/retention.go
  banyand/internal/storage/segment.go
  banyand/internal/storage/shard.go
  banyand/internal/storage/storage.go
  banyand/internal/storage/tsdb.go
Labels: enhancement

#431 docs: generate protobuf api before bydbctl build
  CHANGES.md
  bydbctl/README.md
Labels: documentation

#432 Fix issues found by distributed test
  banyand/internal/storage/index.go
  banyand/internal/storage/index_test.go
  banyand/metadata/client.go
  banyand/metadata/schema/error.go
  banyand/metadata/schema/etcd.go
  banyand/metadata/schema/register_test.go
  banyand/metadata/schema/watcher.go
  banyand/metadata/schema/watcher_test.go
  banyand/queue/pub/client.go
  banyand/queue/pub/pub.go
  pkg/query/logical/stream/stream_plan_distributed.go
  pkg/run/run.go
  pkg/schema/init.go
  test/stress/trace/Makefile
  test/stress/trace/docker-compose-cluster.yaml
  test/stress/trace/docker-compose-single.yaml
  test/stress/trace/trace_suite_test.go
Labels: bug

#433 Add failover process between liaison and data nodes
  .github/workflows/ci.yml
  banyand/dquery/topn.go
  banyand/internal/storage/index_test.go
  banyand/liaison/grpc/measure.go
  banyand/liaison/grpc/server.go
  banyand/liaison/grpc/stream.go
  banyand/measure/topn.go
  banyand/queue/local.go
  banyand/queue/pub/client.go
  banyand/queue/pub/client_test.go
  banyand/queue/pub/pub.go
  banyand/queue/pub/pub_suite_test.go
  banyand/queue/pub/pub_test.go
  banyand/queue/queue.go
  docs/concept/clustering.md
  pkg/bus/bus.go
  pkg/grpchelper/client.go
  pkg/query/logical/measure/measure_plan_distributed.go
  pkg/query/logical/stream/stream_plan_distributed.go
  test/stress/istio/istio_suite_test.go
Labels: documentation, enhancement

#436 Fix flaws found by stream load test
  banyand/internal/storage/index.go
  banyand/internal/storage/retention.go
  banyand/internal/storage/segment.go
  banyand/internal/storage/tsdb.go
  banyand/liaison/grpc/measure.go
  banyand/liaison/grpc/stream.go
  banyand/measure/measure.go
  banyand/measure/write.go
  banyand/stream/index.go
  banyand/stream/iter.go
  banyand/stream/iter_builder.go
  banyand/stream/part.go
  banyand/stream/query.go
  banyand/stream/stream.go
  banyand/stream/tstable.go
  banyand/stream/write.go
  pkg/index/index.go
  pkg/index/inverted/inverted.go
  pkg/index/inverted/inverted_test.go
  pkg/index/inverted/sort.go
  pkg/index/inverted/sort_test.go
  pkg/index/testcases/duration.go
  pkg/index/testcases/service_name.go
  pkg/partition/index.go
  pkg/pb/v1/series.go
  pkg/test/query/metric.go
  pkg/test/query/trace.go
  pkg/timestamp/range.go
  test/cases/stream/data/input/sort_filter.yaml
  test/cases/stream/data/want/sort_filter.yaml
  test/cases/stream/stream.go
  test/docker/base-compose.yml
  test/stress/trace/Makefile
  test/stress/trace/docker-compose-cluster.yaml
  test/stress/trace/docker-compose-single.yaml
  test/stress/trace/trace_suite_test.go
Labels: bug, enhancement

#435 Add document for column-based storage
  CONTRIBUTING.md
  docs/concept/tsdb.md
  docs/installation.md
  docs/installation/binaries.md
Labels: documentation

#439 Fix the wrong server name
  CONTRIBUTING.md
  docs/installation.md
  docs/installation/binaries.md
  docs/installation/cluster.md
  docs/installation/standalone.md
  docs/release.md
Labels: documentation
