Repository apache/skywalking-banyandb, pull requests merged in 2024-08, with the labels that each got.

#504 Merge elements.bin and timestamp.bin
  CHANGES.md
  banyand/measure/block.go
  banyand/stream/block.go
  banyand/stream/block_metadata.go
  banyand/stream/block_metadata_test.go
  banyand/stream/block_reader.go
  banyand/stream/block_test.go
  banyand/stream/block_writer.go
  banyand/stream/part.go
  banyand/stream/snapshot_test.go
  banyand/stream/stream.go
  pkg/encoding/int_list.go
Labels: enhancement

#503 Update kubernetes installation doc
  docs/installation/kubernetes.md
Labels: documentation

#507 Add bydbctl and web-ui interacting guide.
  CHANGES.md
  docs/concept/data-model.md
  docs/crud/measure/query.md
  docs/crud/stream/query.md
  docs/interacting/bydbctl/bydbctl.md
  docs/interacting/bydbctl/property.md
  docs/interacting/bydbctl/query/filter-operation.md
  docs/interacting/bydbctl/query/measure.md
  docs/interacting/bydbctl/query/stream.md
  docs/interacting/bydbctl/schema/group.md
  docs/interacting/bydbctl/schema/index-rule-binding.md
  docs/interacting/bydbctl/schema/index-rule.md
  docs/interacting/bydbctl/schema/measure.md
  docs/interacting/bydbctl/schema/stream.md
  docs/interacting/bydbctl/schema/top-n-aggregation.md
  docs/interacting/java-client.md
  docs/interacting/web-ui/dashboard.md
  docs/interacting/web-ui/property.md
  docs/interacting/web-ui/query/measure.md
  docs/interacting/web-ui/query/stream.md
  docs/interacting/web-ui/schema/group.md
  docs/interacting/web-ui/schema/index-rule-binding.md
  docs/interacting/web-ui/schema/index-rule.md
  docs/interacting/web-ui/schema/measure.md
  docs/interacting/web-ui/schema/stream.md
  docs/interacting/web-ui/schema/top-n-aggregation.md
  docs/menu.yml
Labels: documentation

#505 Merge the query process of series index
  banyand/internal/storage/index.go
  banyand/internal/storage/index_test.go
  banyand/internal/storage/storage.go
  pkg/index/index.go
  pkg/index/inverted/inverted.go
  pkg/index/inverted/inverted_series.go
  pkg/index/inverted/inverted_series_test.go
  pkg/index/inverted/query.go
  pkg/index/inverted/sort.go
  pkg/index/testcases/duration.go
  pkg/query/logical/measure/measure_plan_indexscan_local.go
  pkg/query/model/model.go
Labels: enhancement

#509 fix doc menu
  docs/menu.yml
Labels: documentation

#510 Add deleting data docs
  docs/interacting/bydbctl/schema/top-n-aggregation.md
  docs/interacting/deleting-data.md
  docs/menu.yml
Labels: documentation

#511 Scalability Test and Cluster Management Doc
  CHANGES.md
  docs/menu.yml
  docs/operation/cluster.md
  pkg/node/round_robin.go
  pkg/node/round_robin_test.go
  test/e2e-v2/cases/cluster/e2e.yaml
  test/scale/Makefile
  test/scale/README.md
  test/scale/kind.yaml
  test/scale/measure-default.yaml
  test/scale/oap-pod-xl.yaml
  test/scale/oap-pod.yaml
  test/scale/segment.tpl.json
Labels: documentation, testing

#513 Add failover test
  banyand/queue/sub/sub.go
  docs/operation/cluster.md
  test/failover/Makefile
  test/failover/README.md
  test/failover/check.sh
  test/failover/kind.yaml
  test/failover/oap-pod.yaml
  test/failover/segment.tpl.json
  test/failover/setup.md
Labels: documentation, testing

#479 [ospp] Adds MeasureAggregateFunctionService.Support API
  api/proto/banyandb/database/v1/rpc.proto
  api/proto/banyandb/database/v1/schema.proto
  api/proto/banyandb/model/v1/common.proto
  docs/api-reference.md
Labels: enhancement, api

#516 Add data lifcycle docs
  docs/interacting/data-lifecycle.md
  docs/interacting/deleting-data.md
  docs/menu.yml
Labels: documentation

#515 [GSoC][UI] Fix and show message when group is not exist and native is turned off
  ui/src/views/Dashboard/index.vue
Labels: enhancement, ui

#519 Scheduler metrics and Several Bugs
  CHANGES.md
  banyand/dquery/dquery.go
  banyand/internal/storage/metrics.go
  banyand/internal/storage/segment.go
  banyand/internal/storage/tsdb.go
  banyand/liaison/grpc/metrics.go
  banyand/liaison/grpc/server.go
  banyand/measure/block.go
  banyand/measure/merger_test.go
  banyand/measure/metadata.go
  banyand/measure/query.go
  banyand/observability/service.go
  banyand/stream/metadata.go
  pkg/cmdsetup/liaison.go
  pkg/schema/cache.go
  pkg/schema/metrics.go
  pkg/timestamp/scheduler.go
Labels: bug, enhancement
