Repository apache/skywalking-banyandb, pull requests merged in 2024-12, with the labels that each got.

#561 Fix the bug when adding tags or fields to measuer or stream
  CHANGES.md
  banyand/measure/block.go
  banyand/measure/block_test.go
  banyand/measure/column.go
  banyand/measure/measure_suite_test.go
  banyand/measure/metadata_test.go
  banyand/metadata/schema/error.go
  banyand/metadata/schema/measure.go
  banyand/metadata/schema/stream.go
  banyand/stream/block.go
  banyand/stream/block_test.go
  banyand/stream/metadata_test.go
  banyand/stream/stream_suite_test.go
  banyand/stream/tag.go
  bydbctl/internal/cmd/measure_test.go
  bydbctl/internal/cmd/stream_test.go
  dist/LICENSE
  docs/interacting/bydbctl/schema/measure.md
  docs/interacting/bydbctl/schema/stream.md
  go.mod
  go.sum
  pkg/index/inverted/inverted_series.go
Labels: bug

#562 Index: Use numeric index type to support Int and Float
  CHANGES.md
  banyand/measure/metadata_test.go
  banyand/measure/write.go
  banyand/stream/benchmark_test.go
  banyand/stream/write.go
  dist/LICENSE
  go.mod
  go.sum
  pkg/index/index.go
  pkg/index/inverted/inverted.go
  pkg/index/inverted/inverted_series.go
  pkg/index/inverted/inverted_series_test.go
  pkg/index/inverted/inverted_test.go
  pkg/index/inverted/sort_test.go
  pkg/index/testcases/duration.go
  pkg/index/testcases/service_name.go
  pkg/query/logical/expr_literal.go
  pkg/query/logical/interface.go
  pkg/query/logical/stream/index_filter.go
Labels: enhancement

#563 Fix: polish Index Rule Page and Index Rule Binding Page
  CHANGES.md
  ui/src/components/Editor/index.vue
  ui/src/components/IndexRule/Editor.vue
  ui/src/components/IndexRule/index.vue
  ui/src/components/IndexRuleBinding/Editor.vue
  ui/src/components/IndexRuleBinding/index.vue
  ui/src/components/Property/PropertyRead.vue
  ui/src/components/Read/index.vue
  ui/src/components/TopNAggregation/Editor.vue
  ui/src/components/TopNAggregation/index.vue
  ui/src/styles/elementPlus.scss
Labels: bug

#564 docs: Add `Setting up Environment Variables` in README
  .gitignore
  .licenserc.yaml
  ui/.env.example
  ui/.licenserc.yaml
  ui/README.md
  ui/vite.config.mjs
Labels: documentation

#565 refactor: Add a common component to avoid hard code
  ui/src/components/Editor/index.vue
  ui/src/components/IndexRule/Editor.vue
  ui/src/components/IndexRule/index.vue
  ui/src/components/IndexRuleBinding/Editor.vue
  ui/src/components/IndexRuleBinding/index.vue
  ui/src/components/Property/PropertyRead.vue
  ui/src/components/Property/PropertyValueReader.vue
  ui/src/components/Read/index.vue
  ui/src/components/TopNAggregation/Editor.vue
  ui/src/components/TopNAggregation/index.vue
  ui/src/components/common/FormHeader.vue
Labels: enhancement

#566 Fix View Configuration and remove redundant fields on Property page
  CHANGES.md
  ui/src/components/Property/PropertyEditror.vue
  ui/src/components/Property/PropertyValueReader.vue
  ui/src/components/TopNAggregation/Editor.vue
Labels: bug

#567 Add `indexMode` to display on the measure page
  CHANGES.md
  ui/src/components/Editor/index.vue
Labels: enhancement

#568 feat: Add `NoSort` Field to IndexRule page
  CHANGES.md
  ui/src/components/IndexRule/index.vue
Labels: enhancement

#569 Fix top-n high cardinality
  CHANGES.md
  banyand/measure/topn.go
  banyand/measure/topn_test.go
  banyand/measure/write.go
  banyand/query/processor_topn.go
  pkg/partition/index.go
  pkg/pb/v1/series.go
  pkg/pb/v1/value.go
  pkg/query/logical/measure/topn_analyzer.go
  pkg/query/logical/measure/topn_plan_localscan.go
  pkg/schema/cache.go
  pkg/schema/init.go
  pkg/schema/schema.go
  test/cases/topn/data/want/aggr_desc.yaml
Labels: bug, enhancement

#572 Refactor Groups Tree
  CHANGES.md
  ui/src/components/Aside/index.vue
  ui/src/components/GroupTree/index.vue
  ui/src/components/Header/components/header.vue
  ui/src/components/RightMenu/components/right-menu-item.vue
  ui/src/components/RightMenu/index.vue
  ui/src/components/TopNav/index.vue
  ui/src/views/Measure/index.vue
  ui/src/views/Property/index.vue
  ui/src/views/Stream/index.vue
Labels: bug, enhancement

#573 Fix: Highlight the current node in groups tree
  ui/src/components/GroupTree/index.vue
  ui/src/components/IndexRule/Editor.vue
  ui/src/components/IndexRule/index.vue
  ui/src/components/IndexRuleBinding/Editor.vue
  ui/src/components/IndexRuleBinding/index.vue
  ui/src/components/TopNAggregation/Editor.vue
  ui/src/components/TopNAggregation/index.vue
  ui/src/styles/elementPlus.scss
Labels: bug

#574 build(UI): Add prettier to enforce a consistent style by parsing code
  .github/workflows/ci.yml
  CHANGES.md
  ui/.licenserc.yaml
  ui/.prettierignore
  ui/README.md
  ui/package-lock.json
  ui/package.json
  ui/prettier.config.js
  ui/src/App.vue
  ui/src/api/index.js
  ui/src/assets/base.css
  ui/src/assets/main.css
  ui/src/components/CodeMirror/index.vue
  ui/src/components/Editor/fieldsEditor.vue
  ui/src/components/Editor/index.vue
  ui/src/components/Editor/tagEditor.vue
  ui/src/components/GroupTree/index.vue
  ui/src/components/Header/components/header.vue
  ui/src/components/Header/index.vue
  ui/src/components/IndexRule/Editor.vue
  ui/src/components/IndexRule/index.vue
  ui/src/components/IndexRuleBinding/Editor.vue
  ui/src/components/IndexRuleBinding/index.vue
  ui/src/components/MeasureEditor/index.vue
  ui/src/components/Property/PropertyEditror.vue
  ui/src/components/Property/PropertyRead.vue
  ui/src/components/Property/PropertyValueReader.vue
  ui/src/components/Property/TagEditor.vue
  ui/src/components/Read/index.vue
  ui/src/components/Start/index.vue
  ui/src/components/TopNAggregation/Editor.vue
  ui/src/components/TopNAggregation/index.vue
  ui/src/components/TopNav/index.vue
  ui/src/components/common/FormHeader.vue
  ui/src/main.js
  ui/src/plugins/axios.js
  ui/src/router/index.js
  ui/src/stores/aside.js
  ui/src/stores/header.js
  ui/src/stores/index.js
  ui/src/stores/menuState.js
  ui/src/stores/tags.js
  ui/src/styles/custom.scss
  ui/src/styles/elementPlus.scss
  ui/src/styles/main.scss
  ui/src/utils/axios.js
  ui/src/utils/yaml.js
  ui/src/views/Dashboard/index.vue
  ui/src/views/Errors/NotFound.vue
  ui/src/views/Measure/createEdit.vue
  ui/src/views/Measure/index.vue
  ui/src/views/Measure/measure.vue
  ui/src/views/Property/index.vue
  ui/src/views/Stream/createEdit.vue
  ui/src/views/Stream/index.vue
  ui/src/views/Stream/stream.vue
Labels: enhancement

#575 Fix groups tree for property data
  ui/src/components/Editor/tagEditor.vue
  ui/src/components/GroupTree/index.vue
Labels: bug

#576 Fix schema updating bugs
  CHANGES.md
  banyand/internal/storage/rotation.go
  banyand/internal/storage/segment.go
  banyand/internal/storage/shard.go
  banyand/internal/storage/storage.go
  banyand/internal/storage/tsdb.go
  banyand/internal/storage/tsdb_test.go
  banyand/measure/metadata.go
  banyand/measure/metrics.go
  banyand/metadata/schema/group.go
  banyand/metadata/schema/measure.go
  banyand/metadata/schema/stream.go
  banyand/stream/metadata.go
  banyand/stream/metrics.go
  docs/interacting/bydbctl/schema/group.md
  docs/interacting/bydbctl/schema/measure.md
  docs/interacting/bydbctl/schema/stream.md
  pkg/schema/cache.go
  pkg/schema/schema.go
Labels: bug

#577 Parse string and int array in the query result table
  CHANGES.md
  ui/src/components/GroupTree/index.vue
  ui/src/components/Property/PropertyValueReader.vue
  ui/src/components/Read/index.vue
  ui/vite.config.mjs
Labels: bug

#579 Fix querying the index on a entity tag
  .github/workflows/e2e.storage.yml
  .gitignore
  CHANGES.md
  api/proto/banyandb/measure/v1/rpc.proto
  banyand/measure/measure.go
  banyand/measure/write.go
  pkg/index/inverted/query.go
  test/docker/base-compose.yml
  test/e2e-v2/cases/cluster/storage-cases.yaml
  test/e2e-v2/cases/profiling/ebpf/oncpu/Dockerfile.sqrt
  test/e2e-v2/cases/profiling/ebpf/oncpu/banyandb/docker-compose.yml
  test/e2e-v2/cases/profiling/ebpf/oncpu/banyandb/e2e.yaml
  test/e2e-v2/cases/profiling/ebpf/oncpu/docker-compose.yml
  test/e2e-v2/cases/profiling/ebpf/oncpu/expected/instance.yml
  test/e2e-v2/cases/profiling/ebpf/oncpu/expected/process-estimate-scale.yml
  test/e2e-v2/cases/profiling/ebpf/oncpu/expected/process.yml
  test/e2e-v2/cases/profiling/ebpf/oncpu/expected/profiling-analysis.yml
  test/e2e-v2/cases/profiling/ebpf/oncpu/expected/profiling-create-prepare.yml
  test/e2e-v2/cases/profiling/ebpf/oncpu/expected/profiling-schedule-list.yml
  test/e2e-v2/cases/profiling/ebpf/oncpu/expected/profiling-task-list.yml
  test/e2e-v2/cases/profiling/ebpf/oncpu/profiling-cases.yaml
  test/e2e-v2/cases/profiling/ebpf/oncpu/sqrt.go
  test/e2e-v2/cases/profiling/trace/expected/traces-list.yml
  test/e2e-v2/cases/storage/expected/dependency-endpoint-consumer.yml
  test/e2e-v2/cases/storage/expected/dependency-endpoint-provider.yml
  test/e2e-v2/cases/storage/expected/dependency-instance.yml
  test/e2e-v2/cases/storage/expected/dependency-services-consumer.yml
  test/e2e-v2/cases/storage/expected/dependency-services-provider.yml
  test/e2e-v2/cases/storage/expected/empty-traces-list.yml
  test/e2e-v2/cases/storage/expected/metrics-has-value-percentile.yml
  test/e2e-v2/cases/storage/expected/metrics-has-value.yml
  test/e2e-v2/cases/storage/expected/topN-OP-endpoint.yml
  test/e2e-v2/cases/storage/expected/topN-OP-service.yml
  test/e2e-v2/cases/storage/expected/trace-users-detail.yml
  test/e2e-v2/cases/storage/expected/traces-list.yml
  test/e2e-v2/cases/storage/storage-cases.yaml
  test/e2e-v2/script/env
Labels: bug, testing

#581 Add a cache to improve the performance of the series index write
  CHANGES.md
  banyand/internal/storage/index.go
  banyand/internal/storage/index_test.go
  banyand/internal/storage/rotation.go
  banyand/internal/storage/segment.go
  banyand/internal/storage/tsdb.go
  banyand/measure/measure.go
  banyand/measure/metadata.go
  banyand/measure/service.go
  banyand/stream/metadata.go
  banyand/stream/service.go
  banyand/stream/stream.go
  dist/LICENSE
  dist/licenses/license-github.com-VictoriaMetrics-fastcache.txt
  dist/licenses/license-github.com-golang-snappy.txt
  go.mod
  go.sum
  pkg/index/index.go
  pkg/index/inverted/inverted.go
  pkg/index/inverted/metrics.go
Labels: enhancement

#582 feat(UI): Implement `TopNAggregation` data query page
  CHANGES.md
  ui/src/api/index.js
  ui/src/components/Read/index.vue
  ui/src/components/TopNAggregation/Editor.vue
  ui/src/components/TopNAggregation/index.vue
  ui/src/components/common/data.js
  ui/src/views/Dashboard/index.vue
Labels: enhancement

#583 fix(UI): use `===` instead of `==` to avoid type conversion
  ui/babel.config.js
  ui/index.html
  ui/package.json
  ui/prettier.config.js
  ui/src/components/Editor/fieldsEditor.vue
  ui/src/components/Editor/index.vue
  ui/src/components/Editor/tagEditor.vue
  ui/src/components/GroupTree/index.vue
  ui/src/components/IndexRule/Editor.vue
  ui/src/components/IndexRuleBinding/Editor.vue
  ui/src/components/Property/PropertyEditror.vue
  ui/src/components/Property/PropertyRead.vue
  ui/src/components/Read/index.vue
  ui/src/components/TopNAggregation/Editor.vue
  ui/src/components/TopNav/index.vue
  ui/src/components/common/FormHeader.vue
  ui/src/stores/tags.js
  ui/src/utils/axios.js
  ui/src/utils/yaml.js
  ui/vite.config.mjs
Labels: bug

#584 Remove redundant time range
  pkg/index/inverted/query.go
  pkg/query/logical/measure/measure_plan_indexscan_local.go
  test/cases/measure/data/want/index_mode_all_xl.yaml
  test/cases/measure/measure.go
Labels: bug

#585 Update cespare/xxhash to v2 version
  CHANGES.md
  dist/LICENSE
  dist/licenses/license-github.com-cespare-xxhash.txt
  dist/licenses/license-github.com-spaolacci-murmur3.txt
  go.mod
  go.sum
  pkg/convert/hash.go
  pkg/convert/hash_test.go
  pkg/query/logical/measure/measure_plan_groupby.go
Labels: dependencies
