Repository apache/skywalking-banyandb, pull requests merged in 2024-09, with the labels that each got.

#523 Add a series of docs about operation
  CHANGES.md
  banyand/measure/merger_policy.go
  banyand/measure/service.go
  banyand/observability/metrics_system.go
  banyand/queue/pub/pub.go
  banyand/queue/sub/server.go
  banyand/stream/merger_policy.go
  banyand/stream/service.go
  bydbctl/internal/cmd/group.go
  bydbctl/internal/cmd/health_check.go
  bydbctl/internal/cmd/health_check_test.go
  bydbctl/internal/cmd/index_rule.go
  bydbctl/internal/cmd/index_rule_binding.go
  bydbctl/internal/cmd/measure.go
  bydbctl/internal/cmd/property.go
  bydbctl/internal/cmd/rest.go
  bydbctl/internal/cmd/root.go
  bydbctl/internal/cmd/stream.go
  docs/README.md
  docs/interacting/bydbctl/bydbctl.md
  docs/menu.yml
  docs/operation/configuration.md
  docs/operation/observability.md
  docs/operation/security.md
  docs/operation/system.md
  docs/operation/troubleshooting.md
  docs/operation/upgrade.md
  pkg/test/helpers/http_health.go
  pkg/test/setup/setup.go
  test/integration/distributed/setup/node_test.go
  test/integration/etcd/client_test.go
Labels: documentation

#524 Fix nit in configuration.md
  docs/operation/configuration.md
Labels: documentation

#525 Change etcd default log level
  CHANGES.md
  banyand/metadata/embeddedetcd/server.go
  banyand/metadata/schema/etcd.go
  docs/operation/observability.md
  pkg/logger/logger.go
Labels: chore

#526 Add slow query logging
  CHANGES.md
  banyand/dquery/dquery.go
  banyand/dquery/measure.go
  banyand/dquery/stream.go
  banyand/dquery/topn.go
  banyand/liaison/grpc/measure.go
  banyand/liaison/grpc/stream.go
  banyand/metadata/embeddedetcd/server.go
  banyand/metadata/schema/watcher.go
  banyand/query/processor.go
  banyand/query/processor_topn.go
  banyand/query/query.go
  banyand/queue/sub/sub.go
  docs/operation/configuration.md
  docs/operation/observability.md
  pkg/query/logical/stream/stream_plan_distributed.go
Labels: enhancement

#521 [ospp] Supports measure aggregate function avg and min, and test cases.
  api/proto/banyandb/database/v1/schema.proto
  banyand/measure/aggregate/aggregate_function.go
  banyand/measure/aggregate/avg.go
  banyand/measure/aggregate/avg_test.go
  banyand/measure/aggregate/min.go
  banyand/measure/aggregate/min_test.go
  docs/api-reference.md
Labels: enhancement

#529 Add slim and testing images
  .github/workflows/ci.yml
  .github/workflows/publish-docker.yml
  .github/workflows/test.yml
  CHANGES.md
  Makefile
  banyand/Dockerfile
  banyand/Makefile
  banyand/liaison/http/rpath_empty.go
  banyand/liaison/http/rpath_ui.go
  banyand/liaison/http/server.go
  docs/installation/binaries.md
  docs/installation/docker.md
  scripts/build/build.mk
  scripts/build/docker.mk
  scripts/release.sh
  test/docker/Makefile
  test/e2e-v2/script/docker-compose/base-compose.yml
  ui/Makefile
Labels: docker

#531 Fix tab title of BanyanDB ui
  ui/index.html
Labels: chore, ui

#532 Document how to build images
  docs/installation/docker.md
Labels: documentation

#530 Add benchmarks for topological queries
  pkg/test/query/metric.go
  test/stress/trace/trace_suite_test.go
Labels: testing

#536 Fix duplicated data points in a writing batch
  banyand/measure/block.go
  banyand/measure/block_reader_test.go
  banyand/measure/merger_policy.go
  banyand/measure/merger_test.go
  banyand/measure/part.go
  banyand/measure/tstable_test.go
  banyand/stream/block.go
  banyand/stream/block_reader_test.go
  banyand/stream/merger_policy.go
  banyand/stream/merger_test.go
  banyand/stream/tstable_test.go
Labels: bug

#535 Update release related files
  Makefile
  banyand/measure/part.go
  banyand/measure/tstable_test.go
  banyand/metadata/schema/property.go
  banyand/stream/part.go
  banyand/stream/tstable_test.go
  docs/release.md
  go.mod
  pkg/index/inverted/metrics.go
  scripts/build/build.mk
  scripts/push-release.sh
  scripts/release.sh
Labels: docker

#538 Reconnect to the etcd in the startup phase
  CHANGES.md
  banyand/metadata/client.go
  scripts/push-release.sh
Labels: bug

#539 Support applying the index rule to the tag belonging to the entity
  CHANGES.md
  pkg/index/inverted/inverted_series.go
  pkg/query/logical/parser.go
  pkg/test/measure/testdata/index_rule_bindings/endpoint_traffic.json
  pkg/test/measure/testdata/index_rules/endpoint_name.json
  pkg/test/measure/testdata/measures/endpoint_traffic.json
  test/cases/init.go
  test/cases/measure/data/input/entity_match.yaml
  test/cases/measure/data/testdata/endpoint_traffic.json
  test/cases/measure/data/want/entity_match.yaml
  test/cases/measure/measure.go
Labels: enhancement

#541 Improve the Match Query
  CHANGES.md
  api/proto/banyandb/database/v1/schema.proto
  api/proto/banyandb/model/v1/query.proto
  docs/api-reference.md
  docs/interacting/bydbctl/query/filter-operation.md
  docs/interacting/bydbctl/schema/index-rule.md
  pkg/index/index.go
  pkg/index/inverted/analyzer.go
  pkg/index/inverted/analyzer_test.go
  pkg/index/inverted/inverted.go
  pkg/index/inverted/inverted_test.go
  pkg/index/inverted/query.go
  pkg/query/logical/stream/index_filter.go
  pkg/test/measure/testdata/index_rules/endpoint_name.json
  pkg/test/measure/testdata/index_rules/searchable_name.json
  pkg/test/stream/testdata/index_rules/db.instance.json
  test/cases/measure/data/input/entity_match.yaml
  test/cases/measure/data/testdata/endpoint_traffic.json
  test/cases/measure/data/want/entity_match.yaml
  test/stress/istio/testdata/index-rules/measure-default-index-rule.yaml
  test/stress/istio/testdata/index-rules/measure-minute-index-rule.yaml
  ui/package-lock.json
  ui/src/components/IndexRule/Editor.vue
Labels: enhancement

#543 Add metrics section in ob doc
  docs/operation/grafana-cluster.json
  docs/operation/observability.md
Labels: documentation

#546 Polish troubleshooting docs
  bydbctl/internal/cmd/rest.go
  docs/README.md
  docs/concept/rotation.md
  docs/interacting/data-lifecycle.md
  docs/menu.yml
  docs/operation/configuration.md
  docs/operation/observability.md
  docs/operation/troubleshooting.md
  docs/operation/troubleshooting/crash.md
  docs/operation/troubleshooting/error-checklist.md
  docs/operation/troubleshooting/install.md
  docs/operation/troubleshooting/no-data.md
  docs/operation/troubleshooting/overhead.md
  docs/operation/troubleshooting/query.md
Labels: documentation
