Repository apache/skywalking-banyandb, pull requests merged in 2024-03, with the labels that each got.

#393 Added unit test for hash.go in convert package
  pkg/convert/hash_test.go
Labels: testing

#392 Added unit test for string.go in convert package
  pkg/convert/string_test.go
Labels: testing

#394 Fix slice overflow when querying measure
  .github/workflows/slow-test.yml
  banyand/measure/block.go
  banyand/measure/introducer.go
  banyand/measure/part_metadata.go
  banyand/measure/query.go
  banyand/measure/query_test.go
  banyand/measure/tstable.go
  banyand/measure/tstable_test.go
  banyand/measure/write.go
  pkg/test/measure/testdata/measures/service_latency_minute.json
  test/cases/init.go
  test/cases/measure/data/input/all_latency.yaml
  test/cases/measure/data/testdata/service_latency_minute_data.json
  test/cases/measure/data/want/all_latency.yaml
  test/cases/measure/measure.go
Labels: bug

#399 Remove redundant sync operation in fs
  .github/workflows/flaky-test.yml
  pkg/fs/local_file_system.go
  pkg/fs/local_file_system_nix.go
  pkg/fs/local_file_system_windows.go
  test/stress/cases/istio/istio_suite_test.go
Labels: bug

#402 [UI] Use BanyanDB Browser' Icon and Remove Unused Buttons
  ui/index.html
  ui/public/banyandb.ico
  ui/src/components/Header/components/header.vue
Labels: enhancement

#401 Overlay display wrongly solved
  ui/src/components/Aside/index.vue
Labels: bug

#397 [UI] Default Time Range for Querying Data to Last 15 Minutes.
  ui/src/components/Read/index.vue
  ui/src/views/Measure/index.vue
  ui/src/views/Stream/index.vue
Labels: enhancement, ui

#403 Support generate windows version docker
  .github/workflows/publish-docker.yml
  api/Makefile
  docker/Dockerfile.windows
  pkg/Makefile
  scripts/build/base.mk
  scripts/build/build.mk
  scripts/build/docker.mk
  scripts/build/generate_go.mk
  test/Makefile
Labels: docker

#405 Move part deletion to the close phase
  banyand/measure/gc.go
  banyand/measure/introducer.go
  banyand/measure/part.go
  banyand/measure/query_test.go
  banyand/measure/snapshot.go
  banyand/measure/tstable.go
  banyand/stream/gc.go
  banyand/stream/introducer.go
  banyand/stream/merger_policy.go
  banyand/stream/part.go
  banyand/stream/part_metadata.go
  banyand/stream/query_test.go
  banyand/stream/snapshot.go
  banyand/stream/tstable.go
  pkg/index/inverted/inverted.go
  pkg/index/inverted/inverted_series.go
  pkg/index/inverted/inverted_test.go
Labels: bug

#404 Fix cannot publish windows and linux docker image
  .github/workflows/publish-docker.yml
  Makefile
  api/Makefile
  bydbctl/Makefile
  docker/Dockerfile
  docker/Dockerfile.windows
  scripts/build/base.mk
  scripts/build/build.mk
  scripts/build/docker.mk
  scripts/build/generate_go.mk
Labels: bug

#407 Improve block metadata reading performance
  banyand/measure/block_metadata.go
  banyand/measure/part.go
  banyand/measure/part_iter.go
  banyand/measure/part_iter_test.go
  banyand/measure/query.go
  banyand/measure/query_test.go
  banyand/measure/tstable.go
  banyand/measure/tstable_test.go
  banyand/stream/block_metadata.go
  banyand/stream/part.go
  banyand/stream/part_iter.go
  banyand/stream/part_iter_test.go
  banyand/stream/query.go
  banyand/stream/query_test.go
  banyand/stream/tstable.go
  banyand/stream/tstable_test.go
Labels: bug

#408 Fix console warnings in dev mod, and optimize `vite` configuration for proxy, and remove unused codes
  CHANGES.md
  ui/.gitignore
  ui/src/components/Editor/index.vue
  ui/src/components/Header/components/header.vue
  ui/src/components/Read/index.vue
  ui/vite.config.js
Labels: bug

#411 changed name of children route used for default/notfound route
  ui/src/router/index.js
Labels: bug

#415 Add HTTP services to TopNAggregation operations
  CHANGES.md
  api/proto/banyandb/database/v1/rpc.proto
  banyand/liaison/http/server.go
  docs/api-reference.md
Labels: enhancement

#416 Fix panic when closing banyand
  CHANGES.md
  banyand/measure/metadata.go
  banyand/measure/query.go
  banyand/stream/metadata.go
  banyand/stream/query.go
  pkg/schema/metadata.go
  pkg/wal/README.md
Labels: bug

#417 Added unit test for delta.go in encoding package
  pkg/encoding/delta_test.go
Labels: testing

#418 Add Measure IndexRule and IndexRuleBinding to Measure Page
  ui/src/components/Aside/index.vue
  ui/src/components/IndexRule/Editor.vue
  ui/src/components/IndexRuleBinding/Editor.vue
  ui/src/router/index.js
Labels: ui

#414 Feature to view and download value of property from UI
  ui/src/components/Property/PropertyRead.vue
  ui/src/components/Property/PropertyValueReader.vue
Labels: bug, ui

#421 Added unit test for resize.go in bytes package
  pkg/bytes/resize_test.go
Labels: testing

#422 Add trace stress test suit
  banyand/measure/block.go
  banyand/measure/block_metadata.go
  banyand/measure/part_iter.go
  banyand/measure/part_iter_test.go
  banyand/measure/tstable_test.go
  banyand/stream/block.go
  banyand/stream/block_metadata.go
  banyand/stream/part.go
  banyand/stream/part_iter.go
  banyand/stream/part_iter_test.go
  banyand/stream/tstable.go
  banyand/stream/tstable_test.go
  dist/LICENSE
  dist/licenses/license-github.com-apache-skywalking-cli.txt
  dist/licenses/license-github.com-cpuguy83-go-md2man-v2.txt
  dist/licenses/license-github.com-machinebox-graphql.txt
  dist/licenses/license-github.com-russross-blackfriday-v2.txt
  dist/licenses/license-github.com-urfave-cli-v2.txt
  dist/licenses/license-skywalking.apache.org-repo-goapi.txt
  go.mod
  go.sum
  pkg/query/logical/stream/stream_plan_indexscan_local.go
  pkg/test/query/query.go
  pkg/test/query/trace.go
  test/integration/load/load_suite_test.go
  test/stress/trace/Makefile
  test/stress/trace/docker-compose.yaml
  test/stress/trace/log4j2.xml
  test/stress/trace/segment.tpl.json
  test/stress/trace/trace_suite_test.go
Labels: bug, testing
