Repository apache/skywalking-banyandb, pull requests merged in 2025-04, with the labels that each got.

#637 Fix several issues of stream and bydbctl
  CHANGES.md
  api/common/id.go
  banyand/measure/datapoints.go
  banyand/measure/write.go
  banyand/queue/sub/helpers.go
  banyand/stream/benchmark_test.go
  banyand/stream/block_scanner.go
  banyand/stream/elements.go
  banyand/stream/index.go
  banyand/stream/query.go
  banyand/stream/query_by_ts.go
  banyand/stream/write.go
  bydbctl/internal/cmd/rest.go
  dist/LICENSE
  dist/licenses/license-github.com-go-viper-mapstructure-v2.txt
  dist/licenses/license-github.com-hashicorp-hcl.txt
  dist/licenses/license-github.com-magiconair-properties.txt
  dist/licenses/license-github.com-sagikazarmark-slog-shim.txt
  dist/licenses/license-gopkg.in-ini.v1.txt
  dist/licenses/license-gopkg.in-yaml.v2.txt
  dist/licenses/ui-licenses/license-call-bind-apply-helpers.txt
  dist/licenses/ui-licenses/license-dunder-proto.txt
  dist/licenses/ui-licenses/license-es-define-property.txt
  dist/licenses/ui-licenses/license-es-errors.txt
  dist/licenses/ui-licenses/license-es-object-atoms.txt
  dist/licenses/ui-licenses/license-es-set-tostringtag.txt
  dist/licenses/ui-licenses/license-function-bind.txt
  dist/licenses/ui-licenses/license-get-intrinsic.txt
  dist/licenses/ui-licenses/license-get-proto.txt
  dist/licenses/ui-licenses/license-gopd.txt
  dist/licenses/ui-licenses/license-has-symbols.txt
  dist/licenses/ui-licenses/license-has-tostringtag.txt
  dist/licenses/ui-licenses/license-hasown.txt
  dist/licenses/ui-licenses/license-math-intrinsics.txt
  dist/licenses/ui-licenses/license-sass.txt
  go.mod
  go.sum
  pkg/index/index.go
  pkg/index/inverted/inverted.go
  pkg/index/inverted/inverted_series.go
  pkg/index/inverted/inverted_test.go
  pkg/index/inverted/sort.go
  pkg/index/posting/posting.go
  pkg/index/posting/roaring/roaring.go
  pkg/index/testcases/duration.go
  pkg/index/testcases/service_name.go
  pkg/query/logical/stream/index_filter.go
  pkg/query/logical/stream/stream_plan_tag_filter.go
  scripts/build/version.mk
  test/stress/istio/repo.go
  ui/LICENSE
  ui/package-lock.json
  ui/package.json
Labels: enhancement

#639 Fix NPE
  banyand/stream/index.go
  pkg/query/logical/stream/index_filter.go
Labels: bug

#640 feat(UI): Add the `stages` to `Groups`
  CHANGES.md
  ui/src/components/GroupTree/StageEditor.vue
  ui/src/components/GroupTree/data.js
  ui/src/components/GroupTree/index.vue
Labels: enhancement

#636 Add sharding_key for TopNAggregation source measure
  CHANGES.md
  api/proto/banyandb/database/v1/schema.proto
  banyand/liaison/grpc/discovery.go
  docs/api-reference.md
  pkg/partition/entity.go
  pkg/pb/v1/entity.go
  pkg/test/measure/testdata/measures/service_instance_cpm_minute.json
  pkg/test/measure/testdata/measures/service_instance_endpoint_cpm_minute.json
  test/cases/init.go
Labels: enhancement

#645 Fix a bug and update API
  CHANGES.md
  api/proto/banyandb/common/v1/common.proto
  api/proto/banyandb/measure/v1/query.proto
  api/proto/banyandb/property/v1/rpc.proto
  api/proto/banyandb/stream/v1/query.proto
  api/proto/banyandb/version.go
  banyand/internal/storage/rotation.go
  banyand/internal/storage/rotation_test.go
  banyand/internal/storage/segment.go
  banyand/internal/storage/segment_test.go
  banyand/internal/storage/shard.go
  banyand/internal/storage/storage.go
  banyand/internal/storage/tsdb.go
  banyand/internal/storage/tsdb_test.go
  banyand/liaison/grpc/discovery.go
  banyand/liaison/grpc/measure.go
  banyand/liaison/grpc/stream.go
  banyand/measure/metadata.go
  banyand/measure/query.go
  banyand/queue/pub/pub.go
  banyand/queue/pub/pub_test.go
  banyand/queue/pub/selector.go
  banyand/stream/metadata.go
  banyand/stream/query.go
  docs/api-reference.md
  pkg/bus/bus.go
Labels: bug, api

#647 Add sharding_key for measure in BanyanDB ui
  docs/concept/data-model.md
  ui/src/components/Editor/index.vue
  ui/src/components/Editor/tagEditor.vue
Labels: enhancement, ui

#648 Restore e2e by using latest oap
  .github/workflows/ci.yml
  .github/workflows/test.yml
  test/docker/base-compose.yml
  test/e2e-v2/script/env
  test/stress/classic/env
  test/stress/classic/env.dev
  test/stress/trace/env
Labels: testing

#650 Change `node_selector` to `stages` for groups in UI.
  ui/src/components/Editor/index.vue
  ui/src/components/GroupTree/data.js
  ui/src/components/GroupTree/index.vue
Labels: enhancement

#651 Fix the issue that the etcd watcher gets the historical node registration
  CHANGES.md
  Makefile
  banyand/metadata/schema/etcd.go
  banyand/metadata/schema/schema.go
  banyand/metadata/schema/watcher_test.go
  banyand/queue/pub/pub.go
  pkg/test/flags/flags.go
Labels: bug

#642 Enable Dynamic Reloading of TLS Certificates and Keys
  CHANGES.md
  banyand/liaison/grpc/server.go
  banyand/liaison/http/rpath_empty.go
  banyand/liaison/http/rpath_ui.go
  banyand/liaison/http/server.go
  banyand/queue/pub/pub_test.go
  dist/LICENSE
  docs/operation/security.md
  go.mod
  go.sum
  pkg/tls/cert_util.go
  pkg/tls/reloader.go
  pkg/tls/reloader_test.go
  test/integration/standalone/other/tls_test.go
Labels: enhancement

#655 Add stability checks on recreated files
  pkg/tls/reloader.go
Labels: bug

#646 feat: add TLS support between Liaison and Data nodes with integration…
  banyand/queue/pub/client.go
  banyand/queue/pub/pub.go
  banyand/queue/pub/pub_tls_test.go
  banyand/queue/pub/testdata/certs/README.md
  banyand/queue/pub/testdata/certs/ca.crt
  banyand/queue/pub/testdata/certs/ca.key
  banyand/queue/pub/testdata/certs/cert.conf.template
  banyand/queue/pub/testdata/certs/server.crt
  banyand/queue/pub/testdata/certs/server.key
  docs/operation/configuration.md
  docs/operation/security.md
Labels: enhancement

#657 [WIP] add lifecycle query test
  api/common/id.go
  api/proto/banyandb/measure/v1/topn.proto
  banyand/dquery/dquery.go
  banyand/dquery/measure.go
  banyand/dquery/stream.go
  banyand/dquery/topn.go
  banyand/liaison/grpc/discovery.go
  banyand/liaison/grpc/measure.go
  banyand/liaison/grpc/stream.go
  banyand/queue/pub/pub.go
  docs/api-reference.md
  pkg/cmdsetup/liaison.go
  pkg/query/executor/interface.go
  pkg/query/logical/measure/measure_plan_distributed.go
  pkg/query/logical/stream/stream_plan_distributed.go
  test/docker/Dockerfile
  test/docker/base-compose.yml
  test/e2e-v2/cases/lifecycle/docker-compose.yml
  test/e2e-v2/script/env
Labels: bug, testing

#658 Fix the Measure Fields
  ui/src/components/Read/index.vue
Labels: bug

#656 Feature 12893/add topn subcommand
  banyand/measure/topn.go
  bydbctl/internal/cmd/root.go
  bydbctl/internal/cmd/topn.go
  bydbctl/internal/cmd/topn_test.go
  docs/concept/data-model.md
  docs/interacting/bydbctl/query/top-n-aggregation.md
  docs/interacting/bydbctl/schema/top-n-aggregation.md
  docs/menu.yml
Labels: enhancement

#654 feat(metadata):expose auto-compaction
  banyand/metadata/embeddedetcd/server.go
  banyand/metadata/embeddedserver/server.go
  banyand/metadata/embeddedserver/server_test.go
  banyand/metadata/schema/etcd_test.go
  banyand/metadata/schema/register_test.go
  banyand/metadata/schema/watcher_test.go
  docs/operation/configuration.md
  test/integration/distributed/backup/backup_suite_test.go
  test/integration/distributed/lifecycle/lifecycle_suite_test.go
  test/integration/distributed/query/query_suite_test.go
  test/integration/distributed/setup/setup_suite_test.go
  test/integration/standalone/other/disk_test.go
Labels: bug
