Repository apache/skywalking-banyandb, pull requests merged in 2025-03, with the labels that each got.

#618 Add lifecycle management
  CHANGES.md
  api/common/id.go
  api/data/measure.go
  api/data/stream.go
  api/proto/banyandb/measure/v1/rpc.proto
  api/proto/banyandb/stream/v1/rpc.proto
  banyand/Dockerfile
  banyand/Makefile
  banyand/backup/backup.go
  banyand/backup/backup_test.go
  banyand/backup/lifecycle/lifecycle.go
  banyand/backup/lifecycle/progress.go
  banyand/backup/lifecycle/progress_test.go
  banyand/backup/lifecycle/service.go
  banyand/backup/lifecycle/steps.go
  banyand/backup/lifecycle/steps_test.go
  banyand/backup/restore.go
  banyand/backup/restore_test.go
  banyand/backup/snapshot/snapshot.go
  banyand/cmd/lifecycle/main.go
  banyand/internal/storage/index.go
  banyand/internal/storage/rotation.go
  banyand/internal/storage/segment.go
  banyand/internal/storage/storage.go
  banyand/internal/storage/tsdb.go
  banyand/measure/metadata.go
  banyand/measure/query.go
  banyand/measure/service.go
  banyand/metadata/client.go
  banyand/metadata/embeddedserver/server.go
  banyand/metadata/metadata.go
  banyand/queue/local.go
  banyand/queue/pub/pub.go
  banyand/queue/pub/selector.go
  banyand/queue/pub/selector_test.go
  banyand/queue/queue.go
  banyand/queue/sub/segments.go
  banyand/queue/sub/server.go
  banyand/stream/metadata.go
  banyand/stream/service.go
  banyand/stream/stream.go
  docs/api-reference.md
  docs/menu.yml
  docs/operation/lifecycle.md
  pkg/cmdsetup/data.go
  pkg/cmdsetup/liaison.go
  pkg/index/inverted/inverted_series.go
  pkg/node/interface.go
  pkg/test/helpers/context.go
  pkg/test/measure/testdata/groups/sw_metric.json
  pkg/test/stream/testdata/group.json
  test/cases/lifecycle/lifecycle.go
  test/integration/distributed/lifecycle/lifecycle_suite_test.go
Labels: enhancement

#625 Remove duplicated license header
  banyand/measure/column_metadata.go
  banyand/measure/column_metadata_test.go
Labels: chore

#627 feat: the property page adapts new queries
  ui/src/api/index.js
  ui/src/components/Property/PropertyEditror.vue
  ui/src/components/Property/PropertyRead.vue
  ui/src/components/Property/data.js
  ui/src/styles/custom.scss
Labels: enhancement

#628 feat: change the property page with schema queries
  ui/src/api/index.js
  ui/src/components/Editor/index.vue
  ui/src/components/GroupTree/index.vue
  ui/src/components/IndexRule/Editor.vue
  ui/src/components/IndexRuleBinding/Editor.vue
  ui/src/components/Property/Editor.vue
  ui/src/components/Property/PropertyEditor.vue
  ui/src/components/Property/PropertyRead.vue
  ui/src/components/Property/data.js
  ui/src/components/TopNAggregation/Editor.vue
  ui/src/components/TopNav/index.vue
  ui/src/router/index.js
  ui/src/views/Property/createEdit.vue
Labels: enhancement

#630 Add time range parameters to stream index filter
  CHANGES.md
  pkg/index/index.go
  pkg/index/inverted/inverted.go
  pkg/index/inverted/inverted_series.go
  pkg/index/inverted/query.go
  pkg/index/inverted/sort.go
  pkg/query/logical/stream/index_filter.go
  pkg/query/logical/stream/stream_plan_tag_filter.go
Labels: enhancement

#631 Fix the oom issue when loading too many unnecessary parts into memory
  .asf.yaml
  CHANGES.md
  banyand/stream/block_scanner.go
  banyand/stream/metadata_test.go
  banyand/stream/query_by_ts.go
  banyand/stream/snapshot.go
  banyand/stream/snapshot_test.go
Labels: bug

#635 build(ui): bump up dependencies to fix vulnerabilities
  dist/LICENSE
  ui/LICENSE
  ui/package-lock.json
  ui/package.json
Labels: dependencies
