Repository apache/skywalking-banyandb, pull requests merged in 2025-08, with the labels that each got.

#712 Support background property repair
  api/proto/banyandb/property/v1/gossip.proto
  api/proto/banyandb/property/v1/repair.proto
  banyand/property/db.go
  banyand/property/gossip/client.go
  banyand/property/gossip/message.go
  banyand/property/gossip/server.go
  banyand/property/gossip/service.go
  banyand/property/gossip/service_test.go
  banyand/property/repair.go
  banyand/property/repair_gossip.go
  banyand/property/repair_gossip_test.go
  banyand/property/repair_test.go
  banyand/property/service.go
  banyand/property/shard.go
  banyand/property/shard_test.go
  docs/api-reference.md
  docs/concept/property-repair.md
  pkg/index/inverted/query.go
Labels: enhancement

#716 Implement migration system for both measure and stream data with file-based approach
  CHANGES.md
  api/data/data.go
  api/data/measure.go
  api/data/stream.go
  banyand/backup/lifecycle/measure_migration_visitor.go
  banyand/backup/lifecycle/migration_integration.go
  banyand/backup/lifecycle/progress.go
  banyand/backup/lifecycle/progress_test.go
  banyand/backup/lifecycle/service.go
  banyand/backup/lifecycle/steps.go
  banyand/backup/lifecycle/steps_test.go
  banyand/backup/lifecycle/stream_migration_visitor.go
  banyand/internal/storage/index.go
  banyand/internal/storage/segment.go
  banyand/internal/storage/storage.go
  banyand/internal/storage/visitor.go
  banyand/internal/storage/visitor_test.go
  banyand/measure/part.go
  banyand/measure/part_metadata.go
  banyand/measure/svc_data.go
  banyand/measure/visitor.go
  banyand/measure/write_data.go
  banyand/queue/pub/chunked_sync.go
  banyand/stream/index.go
  banyand/stream/part.go
  banyand/stream/part_metadata.go
  banyand/stream/svc_standalone.go
  banyand/stream/visitor.go
  banyand/stream/visitor_test.go
  banyand/stream/write_data.go
  dist/LICENSE
  go.mod
  go.sum
  pkg/index/index.go
  pkg/index/inverted/inverted.go
Labels: enhancement, api

#694 Push down min/max aggregation operation to data nodes
  CHANGES.md
  pkg/query/logical/measure/measure_analyzer.go
  pkg/query/logical/measure/measure_plan_distributed.go
  test/cases/measure/data/input/group_min.yaml
  test/cases/measure/data/want/group_min.yaml
  test/cases/measure/measure.go
Labels: enhancement

#719 Updated migration visitor constructors to accept target stage interval
  banyand/backup/lifecycle/measure_migration_visitor.go
  banyand/backup/lifecycle/migration_integration.go
  banyand/backup/lifecycle/segment_boundary_utils.go
  banyand/backup/lifecycle/segment_boundary_utils_test.go
  banyand/backup/lifecycle/stream_migration_visitor.go
  banyand/liaison/grpc/measure.go
  banyand/liaison/grpc/property.go
  banyand/liaison/grpc/stream.go
  banyand/measure/introducer.go
  banyand/measure/metadata.go
  banyand/stream/metadata.go
  banyand/stream/tstable.go
  banyand/stream/write_standalone.go
  pkg/fs/local_file_system.go
  pkg/fs/local_file_system_test.go
  pkg/query/logical/stream/stream_plan_distributed.go
  pkg/query/logical/stream/stream_plan_merge.go
  pkg/test/measure/testdata/groups/sw_metric.json
  pkg/test/stream/testdata/group.json
  test/cases/init.go
  test/cases/stream/data/data.go
  test/cases/stream/data/want/all.yaml
  test/cases/stream/data/want/duplicated_all.yaml
  test/cases/stream/data/want/duplicated_entity_filter.yaml
  test/cases/stream/data/want/duplicated_index_filter.yaml
  test/cases/stream/data/want/duplicated_order_by_filter.yaml
  test/cases/stream/data/want/duplicated_order_by_index.yaml
  test/cases/stream/data/want/filter_no_indexed.yaml
  test/cases/stream/data/want/filter_no_indexed_or.yaml
  test/cases/stream/data/want/filter_order_desc.yaml
  test/cases/stream/data/want/filter_tag.yaml
  test/cases/stream/data/want/global_index.yaml
  test/cases/stream/data/want/global_indices.yaml
  test/cases/stream/data/want/having.yaml
  test/cases/stream/data/want/having_non_indexed.yaml
  test/cases/stream/data/want/having_non_indexed_arr.yaml
  test/cases/stream/data/want/less.yaml
  test/cases/stream/data/want/less_eq.yaml
  test/cases/stream/data/want/limit.yaml
  test/cases/stream/data/want/logical.yaml
  test/cases/stream/data/want/offset.yaml
  test/cases/stream/data/want/order_asc.yaml
  test/cases/stream/data/want/order_desc.yaml
  test/cases/stream/data/want/search.yaml
  test/cases/stream/data/want/sort_desc.yaml
  test/cases/stream/data/want/sort_duration_no_index_limit.yaml
  test/cases/stream/data/want/sort_filter.yaml
  test/cases/stream/stream.go
Labels: bug

#717 Feature/Google Cloud Storage Support
  CHANGES.md
  banyand/backup/backup.go
  banyand/backup/restore.go
  banyand/backup/timedir.go
  banyand/measure/topn.go
  dist/LICENSE
  dist/licenses/license-cel.dev-expr.txt
  dist/licenses/license-cloud.google.com-go-auth-oauth2adapt.txt
  dist/licenses/license-cloud.google.com-go-auth.txt
  dist/licenses/license-cloud.google.com-go-compute-metadata.txt
  dist/licenses/license-cloud.google.com-go-iam.txt
  dist/licenses/license-cloud.google.com-go-monitoring.txt
  dist/licenses/license-cloud.google.com-go-storage.txt
  dist/licenses/license-cloud.google.com-go.txt
  dist/licenses/license-github.com-GoogleCloudPlatform-opentelemetry-operations-go-detectors-gcp.txt
  dist/licenses/license-github.com-GoogleCloudPlatform-opentelemetry-operations-go-exporter-metric.txt
  dist/licenses/license-github.com-GoogleCloudPlatform-opentelemetry-operations-go-internal-resourcemapping.txt
  dist/licenses/license-github.com-cncf-xds-go.txt
  dist/licenses/license-github.com-envoyproxy-go-control-plane-envoy.txt
  dist/licenses/license-github.com-felixge-httpsnoop.txt
  dist/licenses/license-github.com-google-s2a-go.txt
  dist/licenses/license-github.com-googleapis-enterprise-certificate-proxy.txt
  dist/licenses/license-github.com-googleapis-gax-go-v2.txt
  dist/licenses/license-github.com-planetscale-vtprotobuf.txt
  dist/licenses/license-go.opentelemetry.io-contrib-detectors-gcp.txt
  dist/licenses/license-go.opentelemetry.io-contrib-instrumentation-net-http-otelhttp.txt
  dist/licenses/license-go.opentelemetry.io-otel-sdk-metric.txt
  dist/licenses/license-golang.org-x-oauth2.txt
  dist/licenses/license-golang.org-x-sync.txt
  dist/licenses/license-google.golang.org-api.txt
  docs/operation/backup.md
  docs/operation/restore.md
  go.mod
  go.sum
  pkg/fs/remote/config/config.go
  pkg/fs/remote/gcp/gcs.go
  pkg/healthcheck/healthcheck.go
  test/cases/backup/all.go
  test/integration/dockertesthelper/constant.go
  test/integration/dockertesthelper/fake-gcs-server.go
  test/stress/classic/Makefile
Labels: enhancement

#714 Introduce Trace System in background repair property feature
  api/proto/banyandb/property/v1/gossip.proto
  banyand/property/gossip/client.go
  banyand/property/gossip/message.go
  banyand/property/gossip/server.go
  banyand/property/gossip/service.go
  banyand/property/gossip/service_test.go
  banyand/property/gossip/trace.go
  banyand/property/repair.go
  banyand/property/repair_gossip.go
  banyand/property/repair_gossip_test.go
  banyand/property/service.go
  banyand/stream/stream_suite_test.go
  banyand/stream/svc_standalone.go
  bydbctl/internal/cmd/property_test.go
  docs/api-reference.md
  pkg/cmdsetup/data.go
  pkg/cmdsetup/standalone.go
  pkg/test/setup/setup.go
Labels: enhancement

#720 fix: correct decode bug in tag.go and column.go
  banyand/measure/column.go
  banyand/measure/column_test.go
  banyand/stream/tag.go
  banyand/stream/tag_test.go
Labels: bug

#721 Enhance flusher and introducer loops to support merging operations
  CHANGES.md
  banyand/measure/flusher.go
  banyand/measure/introducer.go
  banyand/measure/measure.go
  banyand/measure/part.go
  banyand/measure/svc_liaison.go
  banyand/measure/syncer.go
  banyand/measure/topn.go
  banyand/measure/tstable.go
  banyand/measure/wqueue.go
  banyand/protector/protector.go
  banyand/stream/flusher.go
  banyand/stream/introducer.go
  banyand/stream/part.go
  banyand/stream/part_test.go
  banyand/stream/stream.go
  banyand/stream/svc_liaison.go
  banyand/stream/syncer.go
  banyand/stream/tstable.go
  banyand/stream/wqueue.go
  pkg/test/measure/testdata/groups/updated.json
  pkg/test/setup/setup.go
Labels: enhancement

#724 Trace sidx design
  banyand/internal/sidx/DESIGN.md
  banyand/queue/pub/client.go
Labels: documentation

#726 Fix memory leak in measure package
  banyand/measure/block_metadata.go
  banyand/measure/part_iter.go
  banyand/measure/part_iter_test.go
  banyand/measure/query.go
  banyand/measure/query_test.go
  banyand/measure/tstable.go
  banyand/measure/tstable_test.go
Labels: bug

#728 Secondary index for trace(1/6)
  banyand/internal/encoding/tag_encoder.go
  banyand/internal/sidx/DESIGN.md
  banyand/internal/sidx/TODO.md
  banyand/internal/sidx/block.go
  banyand/internal/sidx/block_test.go
  banyand/internal/sidx/element.go
  banyand/internal/sidx/element_test.go
  banyand/internal/sidx/metadata.go
  banyand/internal/sidx/metadata_test.go
  banyand/internal/sidx/part.go
  banyand/internal/sidx/part_test.go
  banyand/internal/sidx/part_wrapper.go
  banyand/internal/sidx/part_wrapper_test.go
  banyand/internal/sidx/tag.go
  banyand/internal/sidx/tag_test.go
  banyand/stream/tag.go
  banyand/stream/tag_test.go
Labels: enhancement

#732 Secondary index for trace: snapshot
  AI_CODING_GUIDELINES.md
  banyand/internal/sidx/DESIGN.md
  banyand/internal/sidx/TODO.md
  banyand/internal/sidx/element.go
  banyand/internal/sidx/element_test.go
  banyand/internal/sidx/introducer.go
  banyand/internal/sidx/introducer_test.go
  banyand/internal/sidx/part_wrapper.go
  banyand/internal/sidx/part_wrapper_test.go
  banyand/internal/sidx/sidx.go
  banyand/internal/sidx/snapshot.go
  banyand/internal/sidx/snapshot_test.go
Labels: enhancement

#737 Add BDSL documentation for BanyanDB Query Language
  .gitignore
  docs/interacting/bydbql.md
  docs/menu.yml
Labels: documentation

#738 Secondary index for trace: query process
  banyand/internal/sidx/TODO.md
  banyand/internal/sidx/block.go
  banyand/internal/sidx/block_scanner.go
  banyand/internal/sidx/block_scanner_test.go
  banyand/internal/sidx/block_test.go
  banyand/internal/sidx/block_writer.go
  banyand/internal/sidx/element.go
  banyand/internal/sidx/element_test.go
  banyand/internal/sidx/integration_test_framework.go
  banyand/internal/sidx/integration_test_framework_test.go
  banyand/internal/sidx/interfaces.go
  banyand/internal/sidx/interfaces_examples.go
  banyand/internal/sidx/interfaces_examples_test.go
  banyand/internal/sidx/iter.go
  banyand/internal/sidx/iter_test.go
  banyand/internal/sidx/metadata.go
  banyand/internal/sidx/metadata_test.go
  banyand/internal/sidx/mock_components.go
  banyand/internal/sidx/mock_components_test.go
  banyand/internal/sidx/mock_sidx.go
  banyand/internal/sidx/mock_sidx_test.go
  banyand/internal/sidx/mock_usage.md
  banyand/internal/sidx/mock_usage_test.go
  banyand/internal/sidx/part.go
  banyand/internal/sidx/part_iter.go
  banyand/internal/sidx/part_iter_test.go
  banyand/internal/sidx/part_test.go
  banyand/internal/sidx/part_wrapper.go
  banyand/internal/sidx/part_wrapper_test.go
  banyand/internal/sidx/query_result.go
  banyand/internal/sidx/query_result_test.go
  banyand/internal/sidx/sidx.go
  banyand/internal/sidx/sidx_test.go
  banyand/internal/sidx/snapshot_test.go
  banyand/internal/sidx/tag.go
  banyand/internal/sidx/tag_filter_op.go
  banyand/internal/sidx/tag_filter_op_test.go
  banyand/internal/sidx/tag_test.go
  banyand/stream/query_by_idx.go
  banyand/stream/query_by_ts.go
Labels: enhancement

#740 Implement atomic counters for total queries and writes in sidx
  banyand/internal/sidx/sidx.go
Labels: bug

#739 Enhance access log functionality with sampling option and add tests
  CHANGES.md
  banyand/liaison/grpc/measure.go
  banyand/liaison/grpc/server.go
  banyand/liaison/grpc/stream.go
  banyand/trace/query_test.go
  docs/operation/configuration.md
  pkg/accesslog/file.go
  pkg/accesslog/file_test.go
Labels: enhancement

#742 Integrate sidx writing, flushing and merging into core trace storage
  banyand/trace/flusher.go
  banyand/trace/merger.go
  banyand/trace/part.go
  banyand/trace/traces.go
  banyand/trace/tstable.go
  banyand/trace/write_liaison.go
  banyand/trace/write_standalone.go
Labels: enhancement

#743 Add query by trace id test case to the trace model
  banyand/internal/sidx/introducer.go
  banyand/internal/sidx/metadata.go
  banyand/internal/sidx/metadata_test.go
  banyand/internal/sidx/part.go
  banyand/internal/sidx/part_test.go
  banyand/internal/sidx/part_wrapper.go
  banyand/internal/sidx/part_wrapper_test.go
  banyand/internal/sidx/query_result_test.go
  banyand/internal/sidx/snapshot.go
  banyand/internal/sidx/snapshot_test.go
  banyand/measure/measure_suite_test.go
  banyand/measure/topn.go
  banyand/query/processor.go
  banyand/query/query.go
  banyand/stream/stream_suite_test.go
  banyand/trace/block.go
  banyand/trace/metadata.go
  banyand/trace/part_iter.go
  banyand/trace/query.go
  banyand/trace/query_test.go
  banyand/trace/trace.go
  banyand/trace/tracing.go
  banyand/trace/tstable.go
  banyand/trace/tstable_test.go
  banyand/trace/write_standalone.go
  pkg/cmdsetup/data.go
  pkg/cmdsetup/standalone.go
  pkg/query/executor/interface.go
  pkg/query/logical/stream/stream_plan_tag_filter.go
  pkg/query/logical/tag_filter.go
  pkg/query/logical/trace/index_filter.go
  pkg/query/logical/trace/schema.go
  pkg/query/logical/trace/trace_analyzer.go
  pkg/query/logical/trace/trace_plan_local.go
  pkg/query/logical/trace/trace_plan_tag_filter.go
  pkg/query/model/model.go
  pkg/schema/cache.go
  test/cases/init.go
  test/cases/trace/data/data.go
  test/cases/trace/data/input/eq_trace_id.yml
  test/cases/trace/data/want/eq_trace_id.yml
  test/cases/trace/trace.go
  test/integration/standalone/query/query_suite_test.go
Labels: testing

#744 Fix unit test TestQueryResult in trace
  banyand/trace/block.go
  banyand/trace/merger.go
  banyand/trace/query_test.go
Labels: bug
