Repository apache/skywalking-banyandb, pull requests merged in 2025-07, with the labels that each got.

#691 Introduce the `Trace` data model to store the trace/span data
  CHANGES.md
  api/proto/banyandb/common/v1/common.proto
  api/proto/banyandb/database/v1/schema.proto
  api/proto/banyandb/model/v1/common.proto
  api/proto/banyandb/trace/v1/query.proto
  api/proto/banyandb/trace/v1/rpc.proto
  api/proto/banyandb/trace/v1/write.proto
  docs/api-reference.md
Labels: api

#693 Support skipping index and tree index in BanyanDB ui
  ui/src/components/IndexRule/Editor.vue
Labels: ui

#666 Add documentation for skipping index
  docs/concept/data-model.md
  docs/concept/tsdb.md
  docs/menu.yml
Labels: documentation

#688 Encode each column based on its data type
  banyand/measure/benchmark_encode_test.go
  banyand/measure/column.go
  banyand/measure/column_test.go
  banyand/measure/part_test.go
  banyand/stream/block_test.go
  banyand/stream/part_test.go
  banyand/stream/tag.go
  banyand/stream/tag_test.go
  pkg/bytes/buffer.go
  pkg/convert/number.go
  pkg/encoding/encoding.go
  pkg/encoding/float.go
  pkg/encoding/float_test.go
Labels: enhancement

#696 Update TSDB version to v1.3.0 in documentation
  docs/concept/tsdb.md
Labels: documentation

#697 Push down aggregation for topN query
  CHANGES.md
  api/proto/banyandb/measure/v1/query.proto
  banyand/query/processor.go
  docs/api-reference.md
  pkg/query/logical/measure/measure_plan_distributed.go
Labels: enhancement

#701 Fix panic in Bloom filter decoding
  banyand/stream/block.go
Labels: bug

#692 Support save repair state tree in property
  banyand/internal/storage/storage.go
  banyand/property/db.go
  banyand/property/repair.go
  banyand/property/repair_test.go
  banyand/property/service.go
  banyand/property/shard.go
  banyand/property/shard_test.go
  pkg/timestamp/scheduler.go
Labels: enhancement

#702 Add the property background repair strategy documentation
  docs/concept/property-repair.md
  docs/menu.yml
  docs/operation/property-repair.md
Labels: documentation

#710 fix(UI): avoid shardingKey.tagNames is undfined
  ui/src/components/Editor/index.vue
Labels: bug

#711 Add chunked data sync to improve memory efficiency and performance during data transfer operations
  CHANGES.md
  api/proto/banyandb/cluster/v1/rpc.proto
  banyand/measure/flusher.go
  banyand/measure/part.go
  banyand/measure/svc_data.go
  banyand/measure/svc_standalone.go
  banyand/measure/syncer.go
  banyand/measure/wqueue_test.go
  banyand/measure/write_data.go
  banyand/measure/write_index.go
  banyand/queue/local.go
  banyand/queue/pub/chunked_sync.go
  banyand/queue/pub/chunked_sync_test.go
  banyand/queue/pub/pub.go
  banyand/queue/queue.go
  banyand/queue/sub/chunked_sync.go
  banyand/queue/sub/chunked_sync_test.go
  banyand/queue/sub/server.go
  banyand/queue/test/chunked_sync_basic_test.go
  banyand/queue/test/chunked_sync_common.go
  banyand/queue/test/chunked_sync_metadata_test.go
  banyand/queue/test/chunked_sync_performance_test.go
  banyand/stream/block_writer.go
  banyand/stream/part.go
  banyand/stream/svc_liaison.go
  banyand/stream/svc_standalone.go
  banyand/stream/syncer.go
  banyand/stream/wqueue_test.go
  banyand/stream/write_data.go
  banyand/stream/write_index.go
  docs/api-reference.md
Labels: enhancement
