Repository apache/skywalking-banyandb, pull requests merged in 2025-09, with the labels that each got.

#747 Change to using pod name as Grafana variable
  docs/operation/grafana-cluster.json
  docs/operation/observability.md
Labels: documentation

#745 Implement sidx flushing and merging
  banyand/internal/sidx/block.go
  banyand/internal/sidx/block_reader.go
  banyand/internal/sidx/block_reader_test.go
  banyand/internal/sidx/gc.go
  banyand/internal/sidx/gc_test.go
  banyand/internal/sidx/interfaces.go
  banyand/internal/sidx/introducer.go
  banyand/internal/sidx/merge.go
  banyand/internal/sidx/metadata.go
  banyand/internal/sidx/multi_sidx_query_test.go
  banyand/internal/sidx/options.go
  banyand/internal/sidx/options_test.go
  banyand/internal/sidx/part.go
  banyand/internal/sidx/part_iter.go
  banyand/internal/sidx/sidx.go
  banyand/internal/sidx/sidx_test.go
  banyand/internal/sidx/snapshot.go
  banyand/internal/sidx/snapshot_test.go
  banyand/trace/flusher.go
  banyand/trace/merger.go
  banyand/trace/merger_test.go
  banyand/trace/tstable.go
  banyand/trace/write_standalone.go
  test/integration/standalone/cold_query/query_suite_test.go
  test/integration/standalone/query_ondisk/query_ondisk_suite_test.go
Labels: enhancement

#750 Implement a resilient publisher
  CHANGES.md
  banyand/queue/pub/batch.go
  banyand/queue/pub/circuitbreaker.go
  banyand/queue/pub/circuitbreaker_test.go
  banyand/queue/pub/client.go
  banyand/queue/pub/client_test.go
  banyand/queue/pub/pub.go
  banyand/queue/pub/pub_suite_test.go
  banyand/queue/pub/pub_test.go
  banyand/queue/pub/retry.go
  banyand/queue/pub/retry_test.go
Labels: enhancement

#752 feat: optimize gRPC message size limits for better time-series data handling
  CHANGES.md
  banyand/liaison/grpc/server.go
  banyand/queue/pub/client.go
Labels: enhancement

#754 Add query access log support
  CHANGES.md
  banyand/liaison/grpc/measure.go
  banyand/liaison/grpc/property.go
  banyand/liaison/grpc/server.go
  banyand/liaison/grpc/stream.go
  banyand/liaison/grpc/trace.go
Labels: enhancement

#756 Fix query access log Unmarshal error
  pkg/accesslog/file.go
  pkg/accesslog/query_log.go
  pkg/accesslog/query_log_test.go
Labels: enhancement

#757 Fix bugs time query range will not automatically update and add some new time query ranges
  ui/src/components/common/data.js
Labels: bug, ui

#774 Fix the unexpected result when querying by traceID and tag belongs to a index rule
  pkg/query/logical/stream/stream_plan_tag_filter.go
  pkg/query/logical/tag_filter.go
  pkg/query/logical/trace/trace_plan_tag_filter.go
  test/cases/trace/data/data.go
  test/cases/trace/data/input/eq_trace_id_and_service_unknown.yml
  test/cases/trace/trace.go
Labels: bug

#775 Fix returning empty result when using IN operator on array type tags
  CHANGES.md
  banyand/internal/sidx/introducer.go
  banyand/internal/sidx/snapshot.go
  banyand/internal/sidx/snapshot_test.go
  pkg/query/logical/stream/index_filter.go
  pkg/query/logical/stream/stream_plan_tag_filter.go
  pkg/query/logical/tag_filter.go
  pkg/query/logical/trace/index_filter.go
  pkg/query/logical/trace/trace_plan_tag_filter.go
  pkg/test/trace/testdata/index_rule_bindings/zipkin.json
  pkg/test/trace/testdata/index_rules/zipkin-duration.json
  pkg/test/trace/testdata/index_rules/zipkin-service.json
  pkg/test/trace/testdata/traces/zipkin.json
  test/cases/init.go
  test/cases/stream/data/input/err_in_arr.yaml
  test/cases/stream/stream.go
  test/cases/trace/data/input/err_in_arr.yml
  test/cases/trace/data/input/having_query_tag.yml
  test/cases/trace/data/testdata/zipkin.json
  test/cases/trace/data/want/having_query_tag.yml
  test/cases/trace/trace.go
Labels: bug

#776 Fix etcd prefix matching any key that starts with this prefix
  CHANGES.md
  banyand/metadata/schema/etcd.go
  banyand/metadata/schema/etcd_test.go
  banyand/metadata/schema/prefix_test.go
Labels: bug

#777 Fix memory leaks and OOM issues in streaming processing
  CHANGES.md
  banyand/measure/write_liaison.go
  banyand/queue/pub/pub.go
  banyand/stream/write_liaison.go
  pkg/flow/dedup_priority_queue.go
  pkg/flow/dedup_priority_queue_test.go
  pkg/flow/streaming/sliding_window.go
  pkg/flow/streaming/sliding_window_test.go
  pkg/flow/types.go
Labels: bug

#779 update trace e2e
  test/e2e-v2/cases/cluster/e2e.yaml
  test/e2e-v2/cases/cluster/storage-cases.yaml
  test/e2e-v2/cases/profiling/trace/expected/traces-v2-list.yml
  test/e2e-v2/cases/profiling/trace/profiling-cases.yaml
  test/e2e-v2/cases/storage/expected/empty-traces-list.yml
  test/e2e-v2/cases/storage/expected/empty-traces-v2-list.yml
  test/e2e-v2/cases/storage/expected/trace-users-detail.yml
  test/e2e-v2/cases/storage/expected/traces-list.yml
  test/e2e-v2/cases/storage/expected/traces-v2-list.yml
  test/e2e-v2/cases/storage/storage-cases.yaml
  test/e2e-v2/script/env
Labels: testing

#785 Fix data race
  banyand/stream/tag_filter.go
Labels: bug

#789 fix(trace): prevent tagType corruption in partMergeIter
  banyand/trace/block_metadata.go
  banyand/trace/block_reader.go
  banyand/trace/block_reader_test.go
  banyand/trace/part_iter.go
Labels: bug

#792 Refactor mergeBlocks function to simplify block handling
  banyand/internal/sidx/merge.go
Labels: bug

#793 Fix the bug that sidx doesn't support array value tags
  .golangci.yml
  banyand/internal/encoding/tag_encoder.go
  banyand/internal/encoding/tag_encoder_test.go
  banyand/internal/sidx/block.go
  banyand/internal/sidx/block_test.go
  banyand/internal/sidx/element.go
  banyand/internal/sidx/interfaces.go
  banyand/internal/sidx/multi_sidx_query_test.go
  banyand/internal/sidx/part.go
  banyand/internal/sidx/sidx_test.go
  banyand/internal/sidx/snapshot.go
  banyand/internal/sidx/tag.go
  banyand/internal/sidx/tag_test.go
  banyand/trace/block.go
  banyand/trace/bloom_filter.go
  banyand/trace/metrics.go
  banyand/trace/snapshot.go
  banyand/trace/syncer.go
  banyand/trace/tag.go
  banyand/trace/trace_suite_test.go
  banyand/trace/traces.go
  banyand/trace/write_data.go
  banyand/trace/write_standalone.go
  test/cases/trace/data/input/having_query_tag_cond.yml
  test/cases/trace/trace.go
Labels: bug

#788 Fix syncSnapshot for trace
  banyand/internal/sidx/sidx.go
  banyand/trace/flusher.go
  banyand/trace/syncer.go
  banyand/trace/write_data.go
  pkg/test/setup/setup.go
  test/integration/distributed/query/query_suite_test.go
Labels: bug

#795 Compressing the Spans of Trace
  banyand/backup/lifecycle/segment_boundary_utils_test.go
  banyand/internal/sidx/TODO.md
  banyand/internal/sidx/block.go
  banyand/internal/sidx/block_writer.go
  banyand/internal/sidx/interfaces.go
  banyand/internal/sidx/introducer.go
  banyand/internal/sidx/introducer_test.go
  banyand/internal/sidx/merge.go
  banyand/internal/sidx/metadata.go
  banyand/internal/sidx/metadata_test.go
  banyand/internal/sidx/multi_sidx_query_test.go
  banyand/internal/sidx/part_iter.go
  banyand/internal/sidx/part_wrapper.go
  banyand/internal/sidx/part_wrapper_test.go
  banyand/internal/sidx/query_result.go
  banyand/internal/sidx/sidx.go
  banyand/internal/sidx/snapshot.go
  banyand/trace/block.go
  banyand/trace/block_test.go
  banyand/trace/merger.go
  banyand/trace/snapshot.go
  test/stress/stream-vs-trace/README.md
  test/stress/stream-vs-trace/benchmark_runner.go
  test/stress/stream-vs-trace/data_generator.go
  test/stress/stream-vs-trace/distribution.go
  test/stress/stream-vs-trace/docker/.gitignore
  test/stress/stream-vs-trace/docker/Dockerfile
  test/stress/stream-vs-trace/docker/Makefile
  test/stress/stream-vs-trace/docker/README.md
  test/stress/stream-vs-trace/docker/client_wrappers.go
  test/stress/stream-vs-trace/docker/collect-stats.sh
  test/stress/stream-vs-trace/docker/docker-compose.yml
  test/stress/stream-vs-trace/docker/docker_test.go
  test/stress/stream-vs-trace/docker/example-stats-output.md
  test/stress/stream-vs-trace/docker/run-docker-test.sh
  test/stress/stream-vs-trace/docker/schema_client.go
  test/stress/stream-vs-trace/docker/wait-for-healthy.sh
  test/stress/stream-vs-trace/metrics.go
  test/stress/stream-vs-trace/schema_loader.go
  test/stress/stream-vs-trace/stream-vs-trace-performance-test-design.md
  test/stress/stream-vs-trace/stream_client.go
  test/stress/stream-vs-trace/stream_vs_trace_suite_test.go
  test/stress/stream-vs-trace/testdata/schema/README.md
  test/stress/stream-vs-trace/testdata/schema/group.json
  test/stress/stream-vs-trace/testdata/schema/stream_index_rule_bindings.json
  test/stress/stream-vs-trace/testdata/schema/stream_index_rules.json
  test/stress/stream-vs-trace/testdata/schema/stream_schema.json
  test/stress/stream-vs-trace/testdata/schema/trace_index_rule_bindings.json
  test/stress/stream-vs-trace/testdata/schema/trace_index_rules.json
  test/stress/stream-vs-trace/testdata/schema/trace_schema.json
  test/stress/stream-vs-trace/trace_client.go
Labels: enhancement
