Repository apache/skywalking-banyandb, pull requests merged in 2025-01, with the labels that each got.

#587 Change Property's storage layer
  CHANGES.md
  api/data/data.go
  api/data/property.go
  api/proto/banyandb/common/v1/common.proto
  api/proto/banyandb/property/v1/property.proto
  api/proto/banyandb/property/v1/rpc.proto
  api/validate/validate.go
  banyand/internal/storage/index.go
  banyand/liaison/grpc/property.go
  banyand/liaison/grpc/server.go
  banyand/metadata/client.go
  banyand/metadata/metadata.go
  banyand/metadata/schema/checker.go
  banyand/metadata/schema/etcd.go
  banyand/metadata/schema/group.go
  banyand/metadata/schema/kind.go
  banyand/metadata/schema/property.go
  banyand/metadata/schema/schema.go
  banyand/property/db.go
  banyand/property/property.go
  banyand/property/service.go
  banyand/property/shard.go
  banyand/queue/pub/pub.go
  bydbctl/internal/cmd/property.go
  bydbctl/internal/cmd/property_test.go
  bydbctl/internal/cmd/rest.go
  bydbctl/internal/cmd/root.go
  docs/api-reference.md
  docs/concept/data-model.md
  docs/interacting/bydbctl/property.md
  pkg/cmdsetup/data.go
  pkg/cmdsetup/standalone.go
  pkg/index/index.go
  pkg/index/inverted/inverted_series.go
  pkg/index/inverted/inverted_series_test.go
  pkg/index/inverted/query.go
  pkg/test/setup/setup.go
  test/docker/base-compose.yml
  test/e2e-v2/script/env
  test/integration/standalone/other/property_test.go
Labels: enhancement

#588 Fix property metric collection failure
  banyand/property/db.go
  test/stress/classic/docker-compose.yaml
Labels: bug

#589 Setup protection to 0.7 release branch
  .asf.yaml
Labels: chore

#590 Add Max Disk Usage Percent
  CHANGES.md
  api/common/id.go
  api/data/data.go
  api/data/measure.go
  api/data/stream.go
  api/proto/banyandb/cluster/v1/rpc.proto
  api/proto/banyandb/measure/v1/write.proto
  api/proto/banyandb/model/v1/write.proto
  api/proto/banyandb/stream/v1/write.proto
  banyand/dquery/measure.go
  banyand/dquery/stream.go
  banyand/dquery/topn.go
  banyand/liaison/grpc/measure.go
  banyand/liaison/grpc/node.go
  banyand/liaison/grpc/node_test.go
  banyand/liaison/grpc/property.go
  banyand/liaison/grpc/registry_test.go
  banyand/liaison/grpc/server.go
  banyand/liaison/grpc/stream.go
  banyand/measure/metadata.go
  banyand/measure/metadata_test.go
  banyand/measure/service.go
  banyand/measure/write.go
  banyand/observability/metrics_system.go
  banyand/observability/service.go
  banyand/observability/type.go
  banyand/property/listener.go
  banyand/property/service.go
  banyand/query/processor.go
  banyand/query/processor_topn.go
  banyand/queue/local.go
  banyand/queue/pub/batch.go
  banyand/queue/pub/client.go
  banyand/queue/pub/client_test.go
  banyand/queue/pub/pub.go
  banyand/queue/pub/pub_suite_test.go
  banyand/queue/pub/pub_test.go
  banyand/queue/queue.go
  banyand/queue/sub/health.go
  banyand/queue/sub/server.go
  banyand/queue/sub/sub.go
  banyand/stream/metadata.go
  banyand/stream/metadata_test.go
  banyand/stream/service.go
  banyand/stream/write.go
  docs/api-reference.md
  docs/operation/troubleshooting/overhead.md
  pkg/bus/bus.go
  pkg/bus/bus_test.go
  pkg/cmdsetup/liaison.go
  pkg/cmdsetup/standalone.go
  pkg/node/round_robin.go
  pkg/node/round_robin_test.go
  pkg/test/setup/setup.go
  test/cases/measure/data/data.go
  test/e2e-v2/script/env
  test/integration/standalone/other/disk_test.go
Labels: enhancement

#591 Add api-version service
  CHANGES.md
  api/proto/banyandb/common/v1/rpc.proto
  api/proto/banyandb/version.go
  banyand/liaison/grpc/api_version.go
  banyand/liaison/grpc/server.go
  banyand/liaison/http/server.go
  banyand/observability/metrics_system.go
  docs/api-reference.md
  scripts/build/base.mk
Labels: api

#593 Fix format
  docs/installation/versions.md
Labels: chore

#594 Another nit
  docs/installation/versions.md
Labels: chore

#595 Wait for the existing registration to be removed before registering
  CHANGES.md
  banyand/metadata/client.go
Labels: enhancement

#596 feat(UI): Update BanyanDB UI to Integrate New Property Query API
  CHANGES.md
  ui/src/api/index.js
  ui/src/components/GroupTree/index.vue
  ui/src/components/Property/PropertyRead.vue
  ui/src/components/TopNAggregation/index.vue
Labels: enhancement

#597 Introduce the batch scan to improve the performance of the query and limit the memory usage
  CHANGES.md
  banyand/measure/topn.go
  banyand/metadata/client.go
  banyand/metadata/schema/etcd.go
  banyand/stream/block.go
  banyand/stream/block_scanner.go
  banyand/stream/index.go
  banyand/stream/merger_policy.go
  banyand/stream/query.go
  banyand/stream/query_by_idx.go
  banyand/stream/query_by_ts.go
  banyand/stream/query_test.go
  banyand/stream/stream.go
  banyand/stream/trace.go
  banyand/stream/tstable_test.go
  pkg/pb/v1/value.go
  pkg/query/logical/optimizer.go
  pkg/query/model/model.go
  pkg/query/model/model_test.go
  pkg/test/measure/etcd.go
  pkg/test/stream/etcd.go
  test/integration/load/load_suite_test.go
  test/stress/istio/testdata/groups/group.yaml
Labels: enhancement
